package api.endpoints;

public class Query {
	
//1 for SignUp with Email
static String signUpWithEmailQuery = "mutation SignUpWithEmail($signUpWithEmailInput: SignUpWithEmailInput!) {\\r\\n"
			+ "  signUpWithEmail(signUpWithEmailInput: $signUpWithEmailInput) {\\r\\n"
			+ "    access_token\\r\\n"
			+ "  }\\r\\n"
			+ "}";

//2 for SignUp with Phone Number
static String signUpWithPhoneQuery ="mutation SignUpWithPhone($signUpWithPhoneInput: SignUpWithPhoneInput!) {\r\n"
		+ "  signUpWithPhone(signUpWithPhoneInput: $signUpWithPhoneInput) {\r\n"
		+ "    access_token\r\n"
		+ "  }\r\n"
		+ "}";
	
//3 for SignUp with Social Media
static String signUpWithSocialQuery ="mutation SignupWithSocial($socialSignupUserInput: SocialSignupUserInput!) {\\r\\n"
			+ "  signupWithSocial(socialSignupUserInput: $socialSignupUserInput) {\\r\\n"
			+ "    access_token\\r\\n"
			+ "  }\\r\\n"
			+ "}";
	
//4 for SignIn with Email
static String signInWithEmailQuery = "mutation SignInWithEmail($signInUserEmailInput: SignInUserEmailInput!) {\\r\\n"
	 		+ "  signInWithEmail(signInUserEmailInput: $signInUserEmailInput) {\\r\\n"
	 		+ "    access_token\\r\\n"
	 		+ "  }\\r\\n"
	 		+ "}";

//5 for SignIn with Phone Number
static String signInWithPhoneQuery ="mutation SignInWithPhone($signInUserPhoneInput: SignInUserPhoneInput!) {\\r\\n"
			+ "  signInWithPhone(signInUserPhoneInput: $signInUserPhoneInput) {\\r\\n"
			+ "    access_token\\r\\n"
			+ "  }\\r\\n"
			+ "}";
	
//6 for SignIn with Social Media
static String signInWithSocialQuery ="mutation SignInWithSocial($socialSigninUserInput: SocialSignInUserInput!) {\\r\\n"
			+ "  signInWithSocial(socialSigninUserInput: $socialSigninUserInput) {\\r\\n"
			+ "    access_token\\r\\n"
			+ "  }\\r\\n"
			+ "}";

// 7 for ADMIN Search Product 
static String adminSearchProductQuery ="{\r\n"
		+ "  adminProductSearch(\r\n"
		+ "    pageNumber: 1\r\n"
		+ "    perPage: 1\r\n"
		+ "    productSearchInput: {}\r\n"
		+ "  ) {\r\n"
		+ "    products {\r\n"
		+ "      _id\r\n"
		+ "      brandName\r\n"
		+ "      category\r\n"
		+ "      costPrice\r\n"
		+ "      createdAt\r\n"
		+ "      currency\r\n"
		+ "      deliveryArea\r\n"
		+ "      deliveryType\r\n"
		+ "      description\r\n"
		+ "      id\r\n"
		+ "      isWishlist\r\n"
		+ "      modified\r\n"
		+ "      offerPrice\r\n"
		+ "      productName\r\n"
		+ "      rating\r\n"
		+ "      runningStock\r\n"
		+ "      salesPrice\r\n"
		+ "      service\r\n"
		+ "      sku\r\n"
		+ "      specificatios\r\n"
		+ "      status\r\n"
		+ "      stockQty\r\n"
		+ "      stockStatus\r\n"
		+ "      tags\r\n"
		+ "      totalQna\r\n"
		+ "      totalRating\r\n"
		+ "      totalSold\r\n"
		+ "    }\r\n"
		+ "    totalCount\r\n"
		+ "  }\r\n"
		+ "}";

//8 home_page>>contest>>PerticularTypeContests
static String perticularTypeContestsQuery ="{\r\n"
		+ "  perticularTypeContests(\r\n"
		+ "    endIndex: 10\r\n"
		+ "    startIndex: 1\r\n"
		+ "    type: \"video\"\r\n"
		+ "  ) {\r\n"
		+ "    start_date\r\n"
		+ "    _id\r\n"
		+ "    beacon_id\r\n"
		+ "    beacons\r\n"
		+ "    beacons_count\r\n"
		+ "    brand {\r\n"
		+ "      _id\r\n"
		+ "      hashtag\r\n"
		+ "      brandtag\r\n"
		+ "      name\r\n"
		+ "      profile_picture\r\n"
		+ "    \r\n"
		+ "    }\r\n"
		+ "    campaign_id\r\n"
		+ "    campaign_type\r\n"
		+ "    country\r\n"
		+ "    cover_image\r\n"
		+ "    cover_image_size {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    description\r\n"
		+ "    end_date\r\n"
		+ "    event\r\n"
		+ "    followers\r\n"
		+ "    full_reward_description\r\n"
		+ "    hashtag\r\n"
		+ "    isactive\r\n"
		+ "    levels\r\n"
		+ "    modified\r\n"
		+ "    name\r\n"
		+ "   \r\n"
		+ "    prize\r\n"
		+ "    rewards {\r\n"
		+ "      giftType\r\n"
		+ "      value\r\n"
		+ "      _id\r\n"
		+ "      onBasis\r\n"
		+ "      rewardFPoint\r\n"
		+ "    }\r\n"
		+ "    snapshot\r\n"
		+ "    snapshot_date\r\n"
		+ "    snapshot_videos\r\n"
		+ "    status\r\n"
		+ "    user {\r\n"
		+ "      _id\r\n"
		+ "      email\r\n"
		+ "    }\r\n"
		+ "    }\r\n"
		+ "}";

//9 home_page>>Brands>>Brands
static String brandsQuery ="{\r\n"
		+ "  perticularTypeContests(\r\n"
		+ "    endIndex: 10\r\n"
		+ "    startIndex: 1\r\n"
		+ "    type: \"video\"\r\n"
		+ "  ) {\r\n"
		+ "    start_date\r\n"
		+ "    _id\r\n"
		+ "    beacon_id\r\n"
		+ "    beacons\r\n"
		+ "    beacons_count\r\n"
		+ "    brand {\r\n"
		+ "      _id\r\n"
		+ "      brandtag\r\n"
		+ "      name\r\n"
		+ "      profile_picture\r\n"
		+ "    \r\n"
		+ "    }\r\n"
		+ "    campaign_id\r\n"
		+ "    campaign_type\r\n"
		+ "    country\r\n"
		+ "    cover_image\r\n"
		+ "    cover_image_size {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    description\r\n"
		+ "    end_date\r\n"
		+ "    event\r\n"
		+ "    followers\r\n"
		+ "    full_reward_description\r\n"
		+ "    hashtag\r\n"
		+ "    isactive\r\n"
		+ "    levels\r\n"
		+ "    modified\r\n"
		+ "    name\r\n"
		+ "    prize\r\n"
		+ "    rewards {\r\n"
		+ "      giftType\r\n"
		+ "      value\r\n"
		+ "    }\r\n"
		+ "    snapshot\r\n"
		+ "    snapshot_date\r\n"
		+ "    snapshot_videos\r\n"
		+ "    status\r\n"
		+ "    user {\r\n"
		+ "      _id\r\n"
		+ "      email\r\n"
		+ "    \r\n"
		+ "    }\r\n"
		+ "    }\r\n"
		+ "}";

//10 home_page>>Offers>>offers
static String offersQuery = "{\r\n"
		+ "  offers(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    brand\r\n"
		+ "    catagory\r\n"
		+ "    image\r\n"
		+ "    link\r\n"
		+ "  }\r\n"
		+ "}";

//11 home_page>>Top Selling>>TopSellingFromTraffic
static String topSellingFromTrafficQuery = "{\r\n"
		+ "  topSellingFromTraffic(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    brand {\r\n"
		+ "      _id\r\n"
		+ "      hashtag\r\n"
		+ "      name\r\n"
		+ "      profile_picture\r\n"
		+ "    }\r\n"
		+ "    categories {\r\n"
		+ "      _id\r\n"
		+ "      name\r\n"
		+ "    }\r\n"
		+ "    clicks_count\r\n"
		+ "    country {\r\n"
		+ "      code\r\n"
		+ "      name\r\n"
		+ "    }\r\n"
		+ "    cta\r\n"
		+ "    currency\r\n"
		+ "    description\r\n"
		+ "    image\r\n"
		+ "    image_size {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    link\r\n"
		+ "    modified\r\n"
		+ "    price\r\n"
		+ "    product_name\r\n"
		+ "    tags\r\n"
		+ "    videos {\r\n"
		+ "      _id\r\n"
		+ "      activeMonetizationStatus\r\n"
		+ "      activity_updated\r\n"
		+ "      adminViewStatus\r\n"
		+ "      allTimeRankingScore\r\n"
		+ "      avgSessionScore\r\n"
		+ "      avgWatchTime\r\n"
		+ "      boosts\r\n"
		+ "      boosts_count\r\n"
		+ "      brandtags\r\n"
		+ "      comments\r\n"
		+ "      comments_count\r\n"
		+ "      coverImageTime\r\n"
		+ "      created_at\r\n"
		+ "      description\r\n"
		+ "      hashtags\r\n"
		+ "      isUserFollowingVideoUploader\r\n"
		+ "      isUserLikedTheVideo\r\n"
		+ "      likes\r\n"
		+ "      likes_count\r\n"
		+ "      magnetic_heading\r\n"
		+ "      modified\r\n"
		+ "      oneMinuteWatchTime\r\n"
		+ "      private\r\n"
		+ "      process_status\r\n"
		+ "      published\r\n"
		+ "      recorded\r\n"
		+ "      removeFromHashtag\r\n"
		+ "      removeFromTrending\r\n"
		+ "      reports_count\r\n"
		+ "      review_status\r\n"
		+ "      shared_count\r\n"
		+ "      shared_users\r\n"
		+ "      short_id\r\n"
		+ "      status\r\n"
		+ "      tagged\r\n"
		+ "      timebomb\r\n"
		+ "      title\r\n"
		+ "      totalEngagementScore\r\n"
		+ "      totalMonetization\r\n"
		+ "      totalReach\r\n"
		+ "      totalViewScore\r\n"
		+ "      totalWatchTime\r\n"
		+ "      trendingScore\r\n"
		+ "      videoScore\r\n"
		+ "      views\r\n"
		+ "      views_count\r\n"
		+ "      watchTimeScore\r\n"
		+ "    }\r\n"
		+ "    views_count\r\n"
		+ "  }\r\n"
		+ "}\r\n"
		+ "";

//12 home_page>>Trending>>TrendingVideos (//live API)
static String trendingVideosTrendingTagQuery = "{\r\n"
		+ "  trendingVideos(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    activeMonetizationStatus\r\n"
		+ "    activity_updated\r\n"
		+ "    adminViewStatus\r\n"
		+ "    adsCampaign {\r\n"
		+ "      campaignType\r\n"
		+ "      id\r\n"
		+ "    }\r\n"
		+ "    allTimeRankingScore\r\n"
		+ "    avgSessionScore\r\n"
		+ "    avgWatchTime\r\n"
		+ "    boosts\r\n"
		+ "    boosts_count\r\n"
		+ "    brandtags\r\n"
		+ "    campaign {\r\n"
		+ "      _id\r\n"
		+ "      country\r\n"
		+ "      description\r\n"
		+ "      hashtag\r\n"
		+ "      name\r\n"
		+ "      short_description\r\n"
		+ "    }\r\n"
		+ "    clickInfoType1 {\r\n"
		+ "      _id\r\n"
		+ "      totalClick\r\n"
		+ "      totalReach\r\n"
		+ "    }\r\n"
		+ "    clickInfoType2 {\r\n"
		+ "      _id\r\n"
		+ "      totalClick\r\n"
		+ "      totalReach\r\n"
		+ "    }\r\n"
		+ "    comments\r\n"
		+ "    comments_count\r\n"
		+ "    coverImageTime\r\n"
		+ "    created_at\r\n"
		+ "    description\r\n"
		+ "    hashtags\r\n"
		+ "    isUserFollowingVideoUploader\r\n"
		+ "    isUserLikedTheVideo\r\n"
		+ "    likes\r\n"
		+ "    likes_count\r\n"
		+ "    location {\r\n"
		+ "      address\r\n"
		+ "      cc\r\n"
		+ "      city\r\n"
		+ "      country\r\n"
		+ "      name\r\n"
		+ "      state\r\n"
		+ "    }\r\n"
		+ "    magnetic_heading\r\n"
		+ "    modified\r\n"
		+ "    oneMinuteWatchTime\r\n"
		+ "    private\r\n"
		+ "    process_status\r\n"
		+ "    products {\r\n"
		+ "      _id\r\n"
		+ "      clicks_count\r\n"
		+ "      cta\r\n"
		+ "      currency\r\n"
		+ "      description\r\n"
		+ "      image\r\n"
		+ "      link\r\n"
		+ "      modified\r\n"
		+ "      price\r\n"
		+ "      product_name\r\n"
		+ "      tags\r\n"
		+ "      views_count\r\n"
		+ "    }\r\n"
		+ "    published\r\n"
		+ "    pushToHashtag {\r\n"
		+ "      actionDate\r\n"
		+ "      remainingDays\r\n"
		+ "      status\r\n"
		+ "    }\r\n"
		+ "    pushToTrending {\r\n"
		+ "      actionDate\r\n"
		+ "      remainingDays\r\n"
		+ "      status\r\n"
		+ "    }\r\n"
		+ "    recorded\r\n"
		+ "    recorded_location {\r\n"
		+ "      coordinates\r\n"
		+ "      type\r\n"
		+ "    }\r\n"
		+ "    removeFromHashtag\r\n"
		+ "    removeFromTrending\r\n"
		+ "    reports {\r\n"
		+ "      from\r\n"
		+ "      reportReason\r\n"
		+ "    }\r\n"
		+ "    reports_count\r\n"
		+ "    review_status\r\n"
		+ "    shared_count\r\n"
		+ "    shared_users\r\n"
		+ "    short_id\r\n"
		+ "    status\r\n"
		+ "    tagged\r\n"
		+ "    timebomb\r\n"
		+ "    title\r\n"
		+ "    totalEngagementScore\r\n"
		+ "    totalMonetization\r\n"
		+ "    totalReach\r\n"
		+ "    totalViewScore\r\n"
		+ "    totalWatchTime\r\n"
		+ "    trendingScore\r\n"
		+ "    user {\r\n"
		+ "      _id\r\n"
		+ "      created_at\r\n"
		+ "      dp\r\n"
		+ "      firebaseRegToken\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "    }\r\n"
		+ "    video {\r\n"
		+ "      cover\r\n"
		+ "      duration\r\n"
		+ "      size\r\n"
		+ "      url\r\n"
		+ "    }\r\n"
		+ "    videoScore\r\n"
		+ "    views\r\n"
		+ "    views_count\r\n"
		+ "    watchTimeScore\r\n"
		+ "  }\r\n"
		+ "}";

//~~*~~*~~*~~*~~*~~13-22 START~~*~~*~~*~~*~~*~~//
static String postStringVideosByHashTag = ", startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    activeMonetizationStatus\r\n"
		+ "    activity_updated\r\n"
		+ "    adminViewStatus\r\n"
		+ "    adsCampaign {\r\n"
		+ "      campaignType\r\n"
		+ "      id\r\n"
		+ "    }\r\n"
		+ "    allTimeRankingScore\r\n"
		+ "    avgSessionScore\r\n"
		+ "    avgWatchTime\r\n"
		+ "    boosts\r\n"
		+ "    boosts_count\r\n"
		+ "    brandtags\r\n"
		+ "    campaign {\r\n"
		+ "      _id\r\n"
		+ "      country\r\n"
		+ "      description\r\n"
		+ "      hashtag\r\n"
		+ "      name\r\n"
		+ "      short_description\r\n"
		+ "    }\r\n"
		+ "    clickInfoType1 {\r\n"
		+ "      _id\r\n"
		+ "      totalClick\r\n"
		+ "      totalReach\r\n"
		+ "    }\r\n"
		+ "    clickInfoType2 {\r\n"
		+ "      _id\r\n"
		+ "      totalClick\r\n"
		+ "      totalReach\r\n"
		+ "    }\r\n"
		+ "    comments\r\n"
		+ "    comments_count\r\n"
		+ "    coverImageTime\r\n"
		+ "    created_at\r\n"
		+ "    description\r\n"
		+ "    hashtags\r\n"
		+ "    isUserFollowingVideoUploader\r\n"
		+ "    isUserLikedTheVideo\r\n"
		+ "    likes\r\n"
		+ "    likes_count\r\n"
		+ "    location {\r\n"
		+ "      address\r\n"
		+ "      cc\r\n"
		+ "      city\r\n"
		+ "      country\r\n"
		+ "      name\r\n"
		+ "      state\r\n"
		+ "    }\r\n"
		+ "    magnetic_heading\r\n"
		+ "    modified\r\n"
		+ "    oneMinuteWatchTime\r\n"
		+ "    private\r\n"
		+ "    process_status\r\n"
		+ "    products {\r\n"
		+ "      _id\r\n"
		+ "      clicks_count\r\n"
		+ "      cta\r\n"
		+ "      currency\r\n"
		+ "      description\r\n"
		+ "      image\r\n"
		+ "      link\r\n"
		+ "      modified\r\n"
		+ "      price\r\n"
		+ "      product_name\r\n"
		+ "      tags\r\n"
		+ "      views_count\r\n"
		+ "    }\r\n"
		+ "    published\r\n"
		+ "    pushToHashtag {\r\n"
		+ "      actionDate\r\n"
		+ "      remainingDays\r\n"
		+ "      status\r\n"
		+ "    }\r\n"
		+ "    pushToTrending {\r\n"
		+ "      actionDate\r\n"
		+ "      remainingDays\r\n"
		+ "      status\r\n"
		+ "    }\r\n"
		+ "    recorded\r\n"
		+ "    recorded_location {\r\n"
		+ "      coordinates\r\n"
		+ "      type\r\n"
		+ "    }\r\n"
		+ "    removeFromHashtag\r\n"
		+ "    removeFromTrending\r\n"
		+ "    reports {\r\n"
		+ "      from\r\n"
		+ "      reportReason\r\n"
		+ "    }\r\n"
		+ "    reports_count\r\n"
		+ "    review_status\r\n"
		+ "    shared_count\r\n"
		+ "    shared_users\r\n"
		+ "    short_id\r\n"
		+ "    status\r\n"
		+ "    tagged\r\n"
		+ "    timebomb\r\n"
		+ "    title\r\n"
		+ "    totalEngagementScore\r\n"
		+ "    totalMonetization\r\n"
		+ "    totalReach\r\n"
		+ "    totalViewScore\r\n"
		+ "    totalWatchTime\r\n"
		+ "    trendingScore\r\n"
		+ "    user {\r\n"
		+ "      _id\r\n"
		+ "      created_at\r\n"
		+ "      dp\r\n"
		+ "      firebaseRegToken\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "    }\r\n"
		+ "    video {\r\n"
		+ "      cover\r\n"
		+ "      duration\r\n"
		+ "      size\r\n"
		+ "      url\r\n"
		+ "    }\r\n"
		+ "    videoScore\r\n"
		+ "    views\r\n"
		+ "    views_count\r\n"
		+ "    watchTimeScore\r\n"
		+ "  }\r\n"
		+ "}";

//13 home_page>>#talent>>VideosByHashTag
static String talentQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#talent\"" + postStringVideosByHashTag ;

//14 home_page>>#beauty>>VideosByHashTag
static String beautyQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#beauty\"" + postStringVideosByHashTag ;

//15 home_page>>#tech>>VideosByHashTag
static String techQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#tech\"" + postStringVideosByHashTag ;

//16 home_page>>#fashion>>VideosByHashTag
static String fashionQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#fashion\"" + postStringVideosByHashTag ;

//17 home_page>>#food>>VideosByHashTag
static String foodQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#food\"" + postStringVideosByHashTag ;

//18 home_page>>#sports>>VideosByHashTag
static String sportsQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#sports\"" + postStringVideosByHashTag ;

//19 home_page>>#smartphone>>VideosByHashTag
static String smartphoneQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#smartphone\"" + postStringVideosByHashTag ;

//20 home_page>>#travel>>VideosByHashTag
static String travelQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#travel\"" + postStringVideosByHashTag ;

//21 home_page>>#decor>>VideosByHashTag
static String decorQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#decor\"" + postStringVideosByHashTag ;

//22 home_page>>#homeappliance>>VideosByHashTag
static String homeapplianceQuery = "{\r\n"
		+ "  videosByHashTag(endIndex: 10, hashtag: \"#homeappliance\"" + postStringVideosByHashTag ;
//~~*~~*~~*~~*~~*~~13-22 END~~*~~*~~*~~*~~*~~//

//23 home_page>>Trending>>TrendingVideos (//live API)
static String trendingVideosNewTagQuery = trendingVideosTrendingTagQuery;

//24 Show All Contests>>My Participation>>MyParticipationContests
static String myParticipationContestsQuery = "";
//24 Query Function ⚡
static public String myParticipationContestsQueryMaker(String contestType, String userId) {
	myParticipationContestsQuery = "{\r\n"
			+ "  myParticipationContests(\r\n"
			+ "    ContestType: \""+contestType+"\"\r\n"
			+ "    endIndex: 1\r\n"
			+ "    startIndex: 1\r\n"
			+ "    userId: \""+userId+"\"\r\n"
			+ "  ) {\r\n"
			+ "    _id\r\n"
			+ "    beacon_id\r\n"
			+ "    beacons\r\n"
			+ "    beacons_count\r\n"
			+ "    brand {\r\n"
			+ "      _id\r\n"
			+ "      brandtag\r\n"
			+ "      hashtag\r\n"
			+ "      name\r\n"
			+ "      profile_picture\r\n"
			+ "      profile_pictures\r\n"
			+ "    }\r\n"
			+ "    campaign_id\r\n"
			+ "    campaign_type\r\n"
			+ "    country\r\n"
			+ "    cover_image\r\n"
			+ "    cover_image_size {\r\n"
			+ "      height\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    cover_video\r\n"
			+ "    description\r\n"
			+ "    end_date\r\n"
			+ "    event\r\n"
			+ "    followers\r\n"
			+ "    full_reward_description\r\n"
			+ "    hashtag\r\n"
			+ "    isLiked\r\n"
			+ "    isResultPublished\r\n"
			+ "    isactive\r\n"
			+ "    levels\r\n"
			+ "    likes {\r\n"
			+ "      _id\r\n"
			+ "      about\r\n"
			+ "      adRevenue\r\n"
			+ "      address1\r\n"
			+ "      address2\r\n"
			+ "      admin\r\n"
			+ "      birth_date\r\n"
			+ "      blocked\r\n"
			+ "      blocked_by\r\n"
			+ "      brand\r\n"
			+ "      brand_stars\r\n"
			+ "      content_creator\r\n"
			+ "      contests\r\n"
			+ "      created_at\r\n"
			+ "      creatorFinalScore\r\n"
			+ "      creatorScore\r\n"
			+ "      currency\r\n"
			+ "      diamond_points\r\n"
			+ "      dp\r\n"
			+ "      email\r\n"
			+ "      experience_points\r\n"
			+ "      f_coins\r\n"
			+ "      featured\r\n"
			+ "      firebaseRegToken\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      following\r\n"
			+ "      followingBrand\r\n"
			+ "      following_brands\r\n"
			+ "      following_brands_count\r\n"
			+ "      following_count\r\n"
			+ "      gender\r\n"
			+ "      influencer\r\n"
			+ "      invited_by\r\n"
			+ "      isFollow\r\n"
			+ "      isSignupWithGoogle\r\n"
			+ "      lastActivityDate\r\n"
			+ "      lastPurchaseDate\r\n"
			+ "      level\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      numberOfBrandStars\r\n"
			+ "      numberOfFriends\r\n"
			+ "      postal\r\n"
			+ "      profile_view\r\n"
			+ "      referredBy\r\n"
			+ "      roles\r\n"
			+ "      signUpType\r\n"
			+ "      status\r\n"
			+ "      totalJoinedCampaign\r\n"
			+ "      totalLikedContest\r\n"
			+ "      totalMonetization\r\n"
			+ "      totalReferReg\r\n"
			+ "      totalWatchTimeOfUser\r\n"
			+ "      uniqeVideoViewCountOfUser\r\n"
			+ "      username\r\n"
			+ "      verified\r\n"
			+ "      videos\r\n"
			+ "    }\r\n"
			+ "    modified\r\n"
			+ "    name\r\n"
			+ "    numberOfRewards\r\n"
			+ "    participants {\r\n"
			+ "      createdAt\r\n"
			+ "    }\r\n"
			+ "    poll {\r\n"
			+ "      _id\r\n"
			+ "      correctAns\r\n"
			+ "      isVoted\r\n"
			+ "      pollNotice\r\n"
			+ "      title\r\n"
			+ "      totalOptions\r\n"
			+ "      totalVote\r\n"
			+ "      votedOption\r\n"
			+ "    }\r\n"
			+ "    prize\r\n"
			+ "    publishPreference\r\n"
			+ "    requestReference\r\n"
			+ "    result {\r\n"
			+ "      createdAt\r\n"
			+ "      isDisburse\r\n"
			+ "      option\r\n"
			+ "    }\r\n"
			+ "    rewardNature\r\n"
			+ "    rewards {\r\n"
			+ "      _id\r\n"
			+ "      giftType\r\n"
			+ "      onBasis\r\n"
			+ "      rewardFPoint\r\n"
			+ "      value\r\n"
			+ "    }\r\n"
			+ "    shortList {\r\n"
			+ "      createdAt\r\n"
			+ "      option\r\n"
			+ "    }\r\n"
			+ "    short_description\r\n"
			+ "    snapshot\r\n"
			+ "    snapshot_date\r\n"
			+ "    snapshot_videos\r\n"
			+ "    start_date\r\n"
			+ "    status\r\n"
			+ "    totalImpression\r\n"
			+ "    totalLike\r\n"
			+ "    totalParticipant\r\n"
			+ "    totalParticipants\r\n"
			+ "    totalReach\r\n"
			+ "    totalResult\r\n"
			+ "    totalRewardValue\r\n"
			+ "    totalShortList\r\n"
			+ "    totalVideoCount\r\n"
			+ "    totalVideoViews\r\n"
			+ "    totalWatchTime\r\n"
			+ "    user {\r\n"
			+ "      _id\r\n"
			+ "      email\r\n"
			+ "      name\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return myParticipationContestsQuery;
}

//25 Show All Contests>>All contest>>PerticularTypeContests
static public String perticularTypeContestsCustomQuery = "{\r\n"
		+ "  perticularTypeContests(\r\n"
		+ "    endIndex: 10\r\n"
		+ "    startIndex: 1\r\n"
		+ "    type: \"video\"\r\n"
		+ "  ) {\r\n"
		+ "    _id\r\n"
		+ "    brand {\r\n"
		+ "      _id\r\n"
		+ "      name\r\n"
		+ "      profile_picture\r\n"
		+ "    }\r\n"
		+ "    campaign_id\r\n"
		+ "    campaign_type\r\n"
		+ "    country\r\n"
		+ "    cover_image\r\n"
		+ "    description\r\n"
		+ "    end_date\r\n"
		+ "    modified\r\n"
		+ "    name\r\n"
		+ "    numberOfRewards\r\n"
		+ "    rewards {\r\n"
		+ "      _id\r\n"
		+ "      giftType\r\n"
		+ "      onBasis\r\n"
		+ "      rewardFPoint\r\n"
		+ "      value\r\n"
		+ "    }\r\n"
		+ "    status\r\n"
		+ "    user {\r\n"
		+ "      _id\r\n"
		+ "      email\r\n"
		+ "      name\r\n"
		+ "    }\r\n"
		+ "  }\r\n"
		+ "}";

//26 Show All Brands>>Click on Show All Brands>>brands(endIndex: $endIndex, startIndex: $startIndex, userId: $userId)
static public String showAllBrandsQuery = "{\r\n"
		+ "  brands(endIndex: 10, startIndex: 1, userId: \"\") {\r\n"
		+ "    _id\r\n"
		+ "    address\r\n"
		+ "    bin\r\n"
		+ "    brandId\r\n"
		+ "    brandUserId\r\n"
		+ "    campaignStartDate\r\n"
		+ "    campaigns\r\n"
		+ "    category\r\n"
		+ "    company_address\r\n"
		+ "    company_name\r\n"
		+ "    contactName\r\n"
		+ "    contact_number\r\n"
		+ "    country\r\n"
		+ "    cover_image\r\n"
		+ "    cover_image_size {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    description\r\n"
		+ "    diamond_points\r\n"
		+ "    email\r\n"
		+ "    f_coins\r\n"
		+ "    followers\r\n"
		+ "    followers_count\r\n"
		+ "    hashtag\r\n"
		+ "    is_follow\r\n"
		+ "    is_master\r\n"
		+ "    manager {\r\n"
		+ "      email\r\n"
		+ "    }\r\n"
		+ "    maxDeliveryTime\r\n"
		+ "    minDeliveryTime\r\n"
		+ "    modified\r\n"
		+ "    name\r\n"
		+ "    nid\r\n"
		+ "    preferedBrandtags\r\n"
		+ "    preferedHashtags\r\n"
		+ "    profile_picture\r\n"
		+ "    profile_picture_size {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    published\r\n"
		+ "    referer {\r\n"
		+ "      _id\r\n"
		+ "      dp\r\n"
		+ "      name\r\n"
		+ "    }\r\n"
		+ "    social\r\n"
		+ "    star_count\r\n"
		+ "    stars {\r\n"
		+ "      _id\r\n"
		+ "      about\r\n"
		+ "      adRevenue\r\n"
		+ "      address1\r\n"
		+ "      address2\r\n"
		+ "      admin\r\n"
		+ "      birth_date\r\n"
		+ "      blocked\r\n"
		+ "      blocked_by\r\n"
		+ "      brand\r\n"
		+ "      brand_stars\r\n"
		+ "      content_creator\r\n"
		+ "      contests\r\n"
		+ "      created_at\r\n"
		+ "      creatorFinalScore\r\n"
		+ "      creatorScore\r\n"
		+ "      currency\r\n"
		+ "      diamond_points\r\n"
		+ "      dp\r\n"
		+ "      email\r\n"
		+ "      experience_points\r\n"
		+ "      f_coins\r\n"
		+ "      featured\r\n"
		+ "      firebaseRegToken\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      following\r\n"
		+ "      followingBrand\r\n"
		+ "      following_brands\r\n"
		+ "      following_brands_count\r\n"
		+ "      following_count\r\n"
		+ "      gender\r\n"
		+ "      influencer\r\n"
		+ "      invited_by\r\n"
		+ "      isFollow\r\n"
		+ "      isSignupWithGoogle\r\n"
		+ "      lastActivityDate\r\n"
		+ "      lastPurchaseDate\r\n"
		+ "      level\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "      numberOfBrandStars\r\n"
		+ "      numberOfFriends\r\n"
		+ "      postal\r\n"
		+ "      profile_view\r\n"
		+ "      referredBy\r\n"
		+ "      roles\r\n"
		+ "      signUpType\r\n"
		+ "      status\r\n"
		+ "      totalJoinedCampaign\r\n"
		+ "      totalLikedContest\r\n"
		+ "      totalMonetization\r\n"
		+ "      totalReferReg\r\n"
		+ "      totalWatchTimeOfUser\r\n"
		+ "      uniqeVideoViewCountOfUser\r\n"
		+ "      username\r\n"
		+ "      verified\r\n"
		+ "      videos\r\n"
		+ "    }\r\n"
		+ "    tin\r\n"
		+ "    type\r\n"
		+ "    url\r\n"
		+ "    varifiedEmail\r\n"
		+ "    varifyStatus\r\n"
		+ "    website\r\n"
		+ "  }\r\n"
		+ "}";

//27 Show All Brands>>Click on Show All Brands>>brand(id: $brandId, userId: $userId)
static public String brandQuery ="";
//27 Query Function ⚡
static public String brandQueryMaker(String brandId, String userId) {
	brandQuery ="{\r\n"
			+ "  brand(id: \""+brandId+"\", userId: \""+userId+"\") {\r\n"
			+ "    _id\r\n"
			+ "    address\r\n"
			+ "    bin\r\n"
			+ "    brandId\r\n"
			+ "    brandUserId\r\n"
			+ "    campaignStartDate\r\n"
			+ "    campaigns\r\n"
			+ "    category\r\n"
			+ "    company_address\r\n"
			+ "    company_name\r\n"
			+ "    contactName\r\n"
			+ "    contact_number\r\n"
			+ "    country\r\n"
			+ "    cover_image\r\n"
			+ "    cover_image_size {\r\n"
			+ "      height\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    description\r\n"
			+ "    diamond_points\r\n"
			+ "    email\r\n"
			+ "    f_coins\r\n"
			+ "    followers\r\n"
			+ "    followers_count\r\n"
			+ "    hashtag\r\n"
			+ "    is_follow\r\n"
			+ "    is_master\r\n"
			+ "    manager {\r\n"
			+ "      email\r\n"
			+ "    }\r\n"
			+ "    maxDeliveryTime\r\n"
			+ "    minDeliveryTime\r\n"
			+ "    modified\r\n"
			+ "    name\r\n"
			+ "    nid\r\n"
			+ "    preferedBrandtags\r\n"
			+ "    preferedHashtags\r\n"
			+ "    profile_picture\r\n"
			+ "    profile_picture_size {\r\n"
			+ "      height\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    published\r\n"
			+ "    referer {\r\n"
			+ "      _id\r\n"
			+ "      dp\r\n"
			+ "      name\r\n"
			+ "    }\r\n"
			+ "    social\r\n"
			+ "    star_count\r\n"
			+ "    stars {\r\n"
			+ "      _id\r\n"
			+ "      about\r\n"
			+ "      adRevenue\r\n"
			+ "      address1\r\n"
			+ "      address2\r\n"
			+ "      admin\r\n"
			+ "      birth_date\r\n"
			+ "      blocked\r\n"
			+ "      blocked_by\r\n"
			+ "      brand\r\n"
			+ "      brand_stars\r\n"
			+ "      content_creator\r\n"
			+ "      contests\r\n"
			+ "      created_at\r\n"
			+ "      creatorFinalScore\r\n"
			+ "      creatorScore\r\n"
			+ "      currency\r\n"
			+ "      diamond_points\r\n"
			+ "      dp\r\n"
			+ "      email\r\n"
			+ "      experience_points\r\n"
			+ "      f_coins\r\n"
			+ "      featured\r\n"
			+ "      firebaseRegToken\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      following\r\n"
			+ "      followingBrand\r\n"
			+ "      following_brands\r\n"
			+ "      following_brands_count\r\n"
			+ "      following_count\r\n"
			+ "      gender\r\n"
			+ "      influencer\r\n"
			+ "      invited_by\r\n"
			+ "      isFollow\r\n"
			+ "      isSignupWithGoogle\r\n"
			+ "      lastActivityDate\r\n"
			+ "      lastPurchaseDate\r\n"
			+ "      level\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      numberOfBrandStars\r\n"
			+ "      numberOfFriends\r\n"
			+ "      postal\r\n"
			+ "      profile_view\r\n"
			+ "      referredBy\r\n"
			+ "      roles\r\n"
			+ "      signUpType\r\n"
			+ "      status\r\n"
			+ "      totalJoinedCampaign\r\n"
			+ "      totalLikedContest\r\n"
			+ "      totalMonetization\r\n"
			+ "      totalReferReg\r\n"
			+ "      totalWatchTimeOfUser\r\n"
			+ "      uniqeVideoViewCountOfUser\r\n"
			+ "      username\r\n"
			+ "      verified\r\n"
			+ "      videos\r\n"
			+ "    }\r\n"
			+ "    tin\r\n"
			+ "    type\r\n"
			+ "    url\r\n"
			+ "    varifiedEmail\r\n"
			+ "    varifyStatus\r\n"
			+ "    website\r\n"
			+ "  }\r\n"
			+ "}";
	return brandQuery;
};

//28 Show All Brands>>Click on Show All Brands>>followBrand(brandId: $brandId)
static public String followBrandQuery ="";
//28 Query Function ⚡
static public String followBrandQueryMaker(String brandId) {
	followBrandQuery ="{\r\n"
			+ "  followBrand(brandId: \""+brandId+"\")\r\n"
			+ "}";
	return followBrandQuery;
}

//29 Show All Brands>>Click on Show All Brands>>unfollowBrand(brandId: $brandId)
static public String unfollowBrandQuery ="";
//29 Query Function ⚡
static public String unfollowBrandQueryMaker(String brandId) {
	unfollowBrandQuery ="{\r\n"
			+ "  unfollowBrand(brandId: \""+brandId+"\")\r\n"
			+ "}";
	return unfollowBrandQuery;
}

//30 Show All Brands>>Click on Show All Brands>>brandContests(brandId: $brandId, endIndex: $endIndex, startIndex:$startIndex)
static public String brandContestsQuery ="";
//30 Query Function ⚡
static public String brandContestsQueryMaker(String brandId) {
	brandContestsQuery = "{\r\n"
			+ "  brandContests(brandId: \""+brandId+"\", endIndex: 10, startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    beacon_id\r\n"
			+ "    beacons\r\n"
			+ "    beacons_count\r\n"
			+ "    brand {\r\n"
			+ "      _id\r\n"
			+ "      brandtag\r\n"
			+ "      hashtag\r\n"
			+ "      name\r\n"
			+ "      profile_picture\r\n"
			+ "      profile_pictures\r\n"
			+ "    }\r\n"
			+ "    campaign_id\r\n"
			+ "    campaign_type\r\n"
			+ "    country\r\n"
			+ "    cover_image\r\n"
			+ "    cover_image_size {\r\n"
			+ "      height\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    cover_video\r\n"
			+ "    description\r\n"
			+ "    end_date\r\n"
			+ "    event\r\n"
			+ "    followers\r\n"
			+ "    full_reward_description\r\n"
			+ "    hashtag\r\n"
			+ "    isLiked\r\n"
			+ "    isResultPublished\r\n"
			+ "    isactive\r\n"
			+ "    levels\r\n"
			+ "    likes {\r\n"
			+ "      _id\r\n"
			+ "      about\r\n"
			+ "      adRevenue\r\n"
			+ "      address1\r\n"
			+ "      address2\r\n"
			+ "      admin\r\n"
			+ "      birth_date\r\n"
			+ "      blocked\r\n"
			+ "      blocked_by\r\n"
			+ "      brand\r\n"
			+ "      brand_stars\r\n"
			+ "      content_creator\r\n"
			+ "      contests\r\n"
			+ "      created_at\r\n"
			+ "      creatorFinalScore\r\n"
			+ "      creatorScore\r\n"
			+ "      currency\r\n"
			+ "      diamond_points\r\n"
			+ "      dp\r\n"
			+ "      email\r\n"
			+ "      experience_points\r\n"
			+ "      f_coins\r\n"
			+ "      featured\r\n"
			+ "      firebaseRegToken\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      following\r\n"
			+ "      followingBrand\r\n"
			+ "      following_brands\r\n"
			+ "      following_brands_count\r\n"
			+ "      following_count\r\n"
			+ "      gender\r\n"
			+ "      influencer\r\n"
			+ "      invited_by\r\n"
			+ "      isFollow\r\n"
			+ "      isSignupWithGoogle\r\n"
			+ "      lastActivityDate\r\n"
			+ "      lastPurchaseDate\r\n"
			+ "      level\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      numberOfBrandStars\r\n"
			+ "      numberOfFriends\r\n"
			+ "      postal\r\n"
			+ "      profile_view\r\n"
			+ "      referredBy\r\n"
			+ "      roles\r\n"
			+ "      signUpType\r\n"
			+ "      status\r\n"
			+ "      totalJoinedCampaign\r\n"
			+ "      totalLikedContest\r\n"
			+ "      totalMonetization\r\n"
			+ "      totalReferReg\r\n"
			+ "      totalWatchTimeOfUser\r\n"
			+ "      uniqeVideoViewCountOfUser\r\n"
			+ "      username\r\n"
			+ "      verified\r\n"
			+ "      videos\r\n"
			+ "    }\r\n"
			+ "    modified\r\n"
			+ "    name\r\n"
			+ "    numberOfRewards\r\n"
			+ "    participants {\r\n"
			+ "      createdAt\r\n"
			+ "    }\r\n"
			+ "    poll {\r\n"
			+ "      _id\r\n"
			+ "      correctAns\r\n"
			+ "      isVoted\r\n"
			+ "      pollNotice\r\n"
			+ "      title\r\n"
			+ "      totalOptions\r\n"
			+ "      totalVote\r\n"
			+ "      votedOption\r\n"
			+ "    }\r\n"
			+ "    prize\r\n"
			+ "    publishPreference\r\n"
			+ "    requestReference\r\n"
			+ "    result {\r\n"
			+ "      createdAt\r\n"
			+ "      isDisburse\r\n"
			+ "      option\r\n"
			+ "    }\r\n"
			+ "    rewardNature\r\n"
			+ "    rewards {\r\n"
			+ "      _id\r\n"
			+ "      giftType\r\n"
			+ "      onBasis\r\n"
			+ "      rewardFPoint\r\n"
			+ "      value\r\n"
			+ "    }\r\n"
			+ "    shortList {\r\n"
			+ "      createdAt\r\n"
			+ "      option\r\n"
			+ "    }\r\n"
			+ "    short_description\r\n"
			+ "    snapshot\r\n"
			+ "    snapshot_date\r\n"
			+ "    snapshot_videos\r\n"
			+ "    start_date\r\n"
			+ "    status\r\n"
			+ "    totalImpression\r\n"
			+ "    totalLike\r\n"
			+ "    totalParticipant\r\n"
			+ "    totalParticipants\r\n"
			+ "    totalReach\r\n"
			+ "    totalResult\r\n"
			+ "    totalRewardValue\r\n"
			+ "    totalShortList\r\n"
			+ "    totalVideoCount\r\n"
			+ "    totalVideoViews\r\n"
			+ "    totalWatchTime\r\n"
			+ "    user {\r\n"
			+ "      _id\r\n"
			+ "      email\r\n"
			+ "      name\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return brandContestsQuery;
}

//31 Contest Detail>>Contests>>ContestDetails($contestDetailsId: String)
static public String contestDetailsQuery ="";
//31 Query Function ⚡
static public String contestDetailsQueryMaker(String contestId) {
	contestDetailsQuery = "{\r\n"
			+ "  contestDetails(id: \""+contestId+"\") {\r\n"
			+ "    _id\r\n"
			+ "    beacon_id\r\n"
			+ "    beacons\r\n"
			+ "    beacons_count\r\n"
			+ "    brand {\r\n"
			+ "      _id\r\n"
			+ "      brandtag\r\n"
			+ "      hashtag\r\n"
			+ "      name\r\n"
			+ "      profile_picture\r\n"
			+ "      profile_pictures\r\n"
			+ "    }\r\n"
			+ "    campaign_id\r\n"
			+ "    campaign_type\r\n"
			+ "    country\r\n"
			+ "    cover_image\r\n"
			+ "    cover_image_size {\r\n"
			+ "      height\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    cover_video\r\n"
			+ "    description\r\n"
			+ "    end_date\r\n"
			+ "    event\r\n"
			+ "    followers\r\n"
			+ "    full_reward_description\r\n"
			+ "    hashtag\r\n"
			+ "    isLiked\r\n"
			+ "    isResultPublished\r\n"
			+ "    isactive\r\n"
			+ "    levels\r\n"
			+ "    likes {\r\n"
			+ "      _id\r\n"
			+ "      about\r\n"
			+ "      adRevenue\r\n"
			+ "      address1\r\n"
			+ "      address2\r\n"
			+ "      admin\r\n"
			+ "      birth_date\r\n"
			+ "      blocked\r\n"
			+ "      blocked_by\r\n"
			+ "      brand\r\n"
			+ "      brand_stars\r\n"
			+ "      content_creator\r\n"
			+ "      contests\r\n"
			+ "      created_at\r\n"
			+ "      creatorFinalScore\r\n"
			+ "      creatorScore\r\n"
			+ "      currency\r\n"
			+ "      diamond_points\r\n"
			+ "      dp\r\n"
			+ "      email\r\n"
			+ "      experience_points\r\n"
			+ "      f_coins\r\n"
			+ "      featured\r\n"
			+ "      firebaseRegToken\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      following\r\n"
			+ "      followingBrand\r\n"
			+ "      following_brands\r\n"
			+ "      following_brands_count\r\n"
			+ "      following_count\r\n"
			+ "      gender\r\n"
			+ "      influencer\r\n"
			+ "      invited_by\r\n"
			+ "      isFollow\r\n"
			+ "      isSignupWithGoogle\r\n"
			+ "      lastActivityDate\r\n"
			+ "      lastPurchaseDate\r\n"
			+ "      level\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      numberOfBrandStars\r\n"
			+ "      numberOfFriends\r\n"
			+ "      postal\r\n"
			+ "      profile_view\r\n"
			+ "      referredBy\r\n"
			+ "      roles\r\n"
			+ "      signUpType\r\n"
			+ "      status\r\n"
			+ "      totalJoinedCampaign\r\n"
			+ "      totalLikedContest\r\n"
			+ "      totalMonetization\r\n"
			+ "      totalReferReg\r\n"
			+ "      totalWatchTimeOfUser\r\n"
			+ "      uniqeVideoViewCountOfUser\r\n"
			+ "      username\r\n"
			+ "      verified\r\n"
			+ "      videos\r\n"
			+ "    }\r\n"
			+ "    modified\r\n"
			+ "    name\r\n"
			+ "    numberOfRewards\r\n"
			+ "    participants {\r\n"
			+ "      createdAt\r\n"
			+ "    }\r\n"
			+ "    poll {\r\n"
			+ "      _id\r\n"
			+ "      correctAns\r\n"
			+ "      isVoted\r\n"
			+ "      pollNotice\r\n"
			+ "      title\r\n"
			+ "      totalOptions\r\n"
			+ "      totalVote\r\n"
			+ "      votedOption\r\n"
			+ "    }\r\n"
			+ "    prize\r\n"
			+ "    publishPreference\r\n"
			+ "    requestReference\r\n"
			+ "    result {\r\n"
			+ "      createdAt\r\n"
			+ "      isDisburse\r\n"
			+ "      option\r\n"
			+ "    }\r\n"
			+ "    rewardNature\r\n"
			+ "    rewards {\r\n"
			+ "      _id\r\n"
			+ "      giftType\r\n"
			+ "      onBasis\r\n"
			+ "      rewardFPoint\r\n"
			+ "      value\r\n"
			+ "    }\r\n"
			+ "    shortList {\r\n"
			+ "      createdAt\r\n"
			+ "      option\r\n"
			+ "    }\r\n"
			+ "    short_description\r\n"
			+ "    snapshot\r\n"
			+ "    snapshot_date\r\n"
			+ "    snapshot_videos\r\n"
			+ "    start_date\r\n"
			+ "    status\r\n"
			+ "    totalImpression\r\n"
			+ "    totalLike\r\n"
			+ "    totalParticipant\r\n"
			+ "    totalParticipants\r\n"
			+ "    totalReach\r\n"
			+ "    totalResult\r\n"
			+ "    totalRewardValue\r\n"
			+ "    totalShortList\r\n"
			+ "    totalVideoCount\r\n"
			+ "    totalVideoViews\r\n"
			+ "    totalWatchTime\r\n"
			+ "    user {\r\n"
			+ "      _id\r\n"
			+ "      email\r\n"
			+ "      name\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return contestDetailsQuery;
}

//32 Contest Detail>>Contest Detail Page>>contestVideos(campaignId:$campaignId, endIndex:$endIndex, startIndex:$startIndex)
static public String detailPageContestVideosQuery ="";
//32 Query Function ⚡
static public String detailPageContestVideosQueryMaker(String contestId) {
	detailPageContestVideosQuery = "{\r\n"
			+ "  contestVideos(campaignId: \""+contestId+"\", endIndex: 10, startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    activeMonetizationStatus\r\n"
			+ "    activity_updated\r\n"
			+ "    adminViewStatus\r\n"
			+ "    adsCampaign {\r\n"
			+ "      campaignType\r\n"
			+ "      id\r\n"
			+ "    }\r\n"
			+ "    allTimeRankingScore\r\n"
			+ "    avgSessionScore\r\n"
			+ "    avgWatchTime\r\n"
			+ "    boosts\r\n"
			+ "    boosts_count\r\n"
			+ "    brandtags\r\n"
			+ "    campaign {\r\n"
			+ "      _id\r\n"
			+ "      country\r\n"
			+ "      description\r\n"
			+ "      hashtag\r\n"
			+ "      name\r\n"
			+ "      short_description\r\n"
			+ "    }\r\n"
			+ "    clickInfoType1 {\r\n"
			+ "      _id\r\n"
			+ "      totalClick\r\n"
			+ "      totalReach\r\n"
			+ "    }\r\n"
			+ "    clickInfoType2 {\r\n"
			+ "      _id\r\n"
			+ "      totalClick\r\n"
			+ "      totalReach\r\n"
			+ "    }\r\n"
			+ "    comments\r\n"
			+ "    comments_count\r\n"
			+ "    coverImageTime\r\n"
			+ "    created_at\r\n"
			+ "    description\r\n"
			+ "    hashtags\r\n"
			+ "    isUserFollowingVideoUploader\r\n"
			+ "    isUserLikedTheVideo\r\n"
			+ "    likes\r\n"
			+ "    likes_count\r\n"
			+ "    location {\r\n"
			+ "      address\r\n"
			+ "      cc\r\n"
			+ "      city\r\n"
			+ "      country\r\n"
			+ "      name\r\n"
			+ "      state\r\n"
			+ "    }\r\n"
			+ "    magnetic_heading\r\n"
			+ "    modified\r\n"
			+ "    oneMinuteWatchTime\r\n"
			+ "    private\r\n"
			+ "    process_status\r\n"
			+ "    products {\r\n"
			+ "      _id\r\n"
			+ "      clicks_count\r\n"
			+ "      cta\r\n"
			+ "      currency\r\n"
			+ "      description\r\n"
			+ "      image\r\n"
			+ "      link\r\n"
			+ "      modified\r\n"
			+ "      price\r\n"
			+ "      product_name\r\n"
			+ "      tags\r\n"
			+ "      views_count\r\n"
			+ "    }\r\n"
			+ "    published\r\n"
			+ "    pushToHashtag {\r\n"
			+ "      actionDate\r\n"
			+ "      remainingDays\r\n"
			+ "      status\r\n"
			+ "    }\r\n"
			+ "    pushToTrending {\r\n"
			+ "      actionDate\r\n"
			+ "      remainingDays\r\n"
			+ "      status\r\n"
			+ "    }\r\n"
			+ "    recorded\r\n"
			+ "    recorded_location {\r\n"
			+ "      coordinates\r\n"
			+ "      type\r\n"
			+ "    }\r\n"
			+ "    removeFromHashtag\r\n"
			+ "    removeFromTrending\r\n"
			+ "    reports {\r\n"
			+ "      from\r\n"
			+ "      reportReason\r\n"
			+ "    }\r\n"
			+ "    reports_count\r\n"
			+ "    review_status\r\n"
			+ "    shared_count\r\n"
			+ "    shared_users\r\n"
			+ "    short_id\r\n"
			+ "    status\r\n"
			+ "    tagged\r\n"
			+ "    timebomb\r\n"
			+ "    title\r\n"
			+ "    totalEngagementScore\r\n"
			+ "    totalMonetization\r\n"
			+ "    totalReach\r\n"
			+ "    totalViewScore\r\n"
			+ "    totalWatchTime\r\n"
			+ "    trendingScore\r\n"
			+ "    user {\r\n"
			+ "      _id\r\n"
			+ "      created_at\r\n"
			+ "      dp\r\n"
			+ "      firebaseRegToken\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "    }\r\n"
			+ "    video {\r\n"
			+ "      cover\r\n"
			+ "      duration\r\n"
			+ "      size\r\n"
			+ "      url\r\n"
			+ "    }\r\n"
			+ "    videoScore\r\n"
			+ "    views\r\n"
			+ "    views_count\r\n"
			+ "    watchTimeScore\r\n"
			+ "  }\r\n"
			+ "}";
	return detailPageContestVideosQuery;
}

//33 Playlist>>Top Users>>topUsers
static public String topUsersQuery = "{\r\n"
		+ "  topUsers {\r\n"
		+ "    _id\r\n"
		+ "    name\r\n"
		+ "  }\r\n"
		+ "}";

//34 Playlist>>Playlist videos>>videoList(videoListInputDto: $videoListInputDto)
//35 Playlist>>List Video Types>>listVideoTypes
static public String listVideoTypesQuery = "{\r\n"
		+ "  listVideoTypes {\r\n"
		+ "    name\r\n"
		+ "    value\r\n"
		+ "  }\r\n"
		+ "}";

//36 Search>>Search User>>searchUser(endIndex: 10,  startIndex: 1, query:"")
static public String searchUserQuery = "";
//36 Query Function ⚡
static public String searchUserQueryMaker(String inputString) {
	searchUserQuery = "{\r\n"
			+ "  searchUser(endIndex: 10, query: \""+inputString+"\", startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    dp\r\n"
			+ "    name\r\n"
			+ "  }\r\n"
			+ "}";
	return searchUserQuery;
}

//37 Search>>Search Video Hashtag>>searchVideoHashtag(endIndex: $endIndex, query: $query, startIndex: $startIndex)
static public String searchVideoHashtagQuery = "";
//37 Query Function ⚡
static public String searchVideoHashtagQueryMaker(String hashtagString) {
	searchVideoHashtagQuery = "{\r\n"
			+ "  searchVideoHashtag(endIndex: 10, query: \""+hashtagString+"\", startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    totalView\r\n"
			+ "  }\r\n"
			+ "}";
	return searchVideoHashtagQuery;
}

//38 Search>>Search Video>>searchVideo(endIndex: 10, query: "Biriyani", startIndex: 1)
static public String searchVideoQuery = "";
//38 Query Function ⚡
static public String searchVideoQueryMaker(String videoTitleString) {
	searchVideoQuery = "{\r\n"
			+ "  searchVideo(endIndex: 10, query: \""+videoTitleString+"\", startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    hashtags\r\n"
			+ "    title\r\n"
			+ "    video {\r\n"
			+ "      cover\r\n"
			+ "      duration\r\n"
			+ "      size\r\n"
			+ "      url\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return searchVideoQuery;
}

//39 Search>>Search Contest>>searchContest(endIndex: 10, query: "My Cell", startIndex: 1)
static public String searchContestQuery = "";
//39 Query Function ⚡
static public String searchContestQueryMaker(String contestTitleString) {
	searchContestQuery = "{\r\n"
			+ "  searchContest(endIndex: 10, query: \""+contestTitleString+"\", startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    brand {\r\n"
			+ "      _id\r\n"
			+ "      brandtag\r\n"
			+ "      name\r\n"
			+ "      profile_picture\r\n"
			+ "    }\r\n"
			+ "    cover_image\r\n"
			+ "    cover_image_size {\r\n"
			+ "      height\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    end_date\r\n"
			+ "    name\r\n"
			+ "  }\r\n"
			+ "}";
	return searchContestQuery;
} 

//40 Video>>Click on Video Comments>>showCommentsForVideo(videoId: $showCommentsForVideoId)
static public String showCommentsForVideoQuery = "";
//40 Query Function ⚡
static public String showCommentsForVideoQueryMaker(String videoId) {
	showCommentsForVideoQuery = "{\r\n"
			+ "  showCommentsForVideo(videoId: \""+videoId+"\") {\r\n"
			+ "    _id\r\n"
			+ "    comment\r\n"
			+ "    created_at\r\n"
			+ "    isReply\r\n"
			+ "    isUserLikedTheComment\r\n"
			+ "    liked_users\r\n"
			+ "    likes_count\r\n"
			+ "    modified\r\n"
			+ "    present {\r\n"
			+ "      _id\r\n"
			+ "      activeMonetizationStatus\r\n"
			+ "      activity_updated\r\n"
			+ "      adminViewStatus\r\n"
			+ "      allTimeRankingScore\r\n"
			+ "      avgSessionScore\r\n"
			+ "      avgWatchTime\r\n"
			+ "      boosts\r\n"
			+ "      boosts_count\r\n"
			+ "      brandtags\r\n"
			+ "      comments\r\n"
			+ "      comments_count\r\n"
			+ "      coverImageTime\r\n"
			+ "      created_at\r\n"
			+ "      description\r\n"
			+ "      hashtags\r\n"
			+ "      isUserFollowingVideoUploader\r\n"
			+ "      isUserLikedTheVideo\r\n"
			+ "      likes\r\n"
			+ "      likes_count\r\n"
			+ "      magnetic_heading\r\n"
			+ "      modified\r\n"
			+ "      oneMinuteWatchTime\r\n"
			+ "      private\r\n"
			+ "      process_status\r\n"
			+ "      published\r\n"
			+ "      recorded\r\n"
			+ "      removeFromHashtag\r\n"
			+ "      removeFromTrending\r\n"
			+ "      reports_count\r\n"
			+ "      review_status\r\n"
			+ "      shared_count\r\n"
			+ "      shared_users\r\n"
			+ "      short_id\r\n"
			+ "      status\r\n"
			+ "      tagged\r\n"
			+ "      timebomb\r\n"
			+ "      title\r\n"
			+ "      totalEngagementScore\r\n"
			+ "      totalMonetization\r\n"
			+ "      totalReach\r\n"
			+ "      totalViewScore\r\n"
			+ "      totalWatchTime\r\n"
			+ "      trendingScore\r\n"
			+ "      videoScore\r\n"
			+ "      views\r\n"
			+ "      views_count\r\n"
			+ "      watchTimeScore\r\n"
			+ "    }\r\n"
			+ "    reply {\r\n"
			+ "      _id\r\n"
			+ "      comment\r\n"
			+ "      created_at\r\n"
			+ "      isReply\r\n"
			+ "      isUserLikedTheComment\r\n"
			+ "      liked_users\r\n"
			+ "      likes_count\r\n"
			+ "      modified\r\n"
			+ "      reports\r\n"
			+ "      reports_count\r\n"
			+ "      tagged\r\n"
			+ "    }\r\n"
			+ "    reports\r\n"
			+ "    reports_count\r\n"
			+ "    tagged\r\n"
			+ "    user {\r\n"
			+ "      _id\r\n"
			+ "      dp\r\n"
			+ "      name\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return showCommentsForVideoQuery;
}

//41 Video>>Get Video Details>>singleVideo(videoId: $videoId) 
static public String singleVideoQuery = "";
//41 Query Function ⚡
static public String singleVideoQueryMaker(String videoId) {
	singleVideoQuery = "{\r\n"
			+ "  singleVideo(videoId: \""+videoId+"\") {\r\n"
			+ "    _id\r\n"
			+ "    comments_count\r\n"
			+ "    hashtags\r\n"
			+ "    isUserFollowingVideoUploader\r\n"
			+ "    isUserLikedTheVideo\r\n"
			+ "    likes\r\n"
			+ "    likes_count\r\n"
			+ "    title\r\n"
			+ "    user {\r\n"
			+ "      _id\r\n"
			+ "      created_at\r\n"
			+ "      dp\r\n"
			+ "      firebaseRegToken\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "    }\r\n"
			+ "    video {\r\n"
			+ "      cover\r\n"
			+ "      duration\r\n"
			+ "      size\r\n"
			+ "      url\r\n"
			+ "    }\r\n"
			+ "    views_count\r\n"
			+ "  }\r\n"
			+ "}";
	return singleVideoQuery;
} 

//42 Notification>>On Fetching Notification>>showNotificationList(endIndex: $endIndex, showNotificationTypeInput: $showNotificationTypeInput, startIndex: $startIndex)
static public String showNotificationListQuery = "{\r\n"
		+ "  showNotificationList(\r\n"
		+ "    endIndex: 10\r\n"
		+ "    showNotificationTypeInput: { notificationType: MYOFFERS }\r\n"
		+ "    startIndex: 1\r\n"
		+ "  ) {\r\n"
		+ "    name\r\n"
		+ "    notificationFrom\r\n"
		+ "    notificationMessage\r\n"
		+ "    notificationType\r\n"
		+ "    refarence\r\n"
		+ "    route\r\n"
		+ "    topicName\r\n"
		+ "    userId\r\n"
		+ "    videoId\r\n"
		+ "  }\r\n"
		+ "}";

//43 Fshop>>cart>>cartProducts  *AUTH
static String cartProductsQuery = "{\r\n"
		+ "  cartProducts {\r\n"
		+ "    products {\r\n"
		+ "      quantity\r\n"
		+ "    }\r\n"
		+ "    user\r\n"
		+ "  }\r\n"
		+ "}";

//44 Fshop>>dashboard>>shippingAddresses  *AUTH
static String shippingAddressesQuery = "{\r\n"
		+ "  shippingAddresses {\r\n"
		+ "    _id\r\n"
		+ "    area\r\n"
		+ "    contactNumber\r\n"
		+ "    country\r\n"
		+ "    district\r\n"
		+ "    email\r\n"
		+ "    name\r\n"
		+ "    policeStation\r\n"
		+ "    postCode\r\n"
		+ "    village\r\n"
		+ "  }\r\n"
		+ "}";

//45 Fshop>>dashboard>>reviewByUser  *AUTH
static String reviewByUserQuery = "\r\n"
		+ "{\r\n"
		+ "  reviewByUser {\r\n"
		+ "    _id\r\n"
		+ "    createdAt\r\n"
		+ "    description\r\n"
		+ "    images {\r\n"
		+ "      height\r\n"
		+ "      image\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    product {\r\n"
		+ "      _id\r\n"
		+ "      brandName\r\n"
		+ "      category\r\n"
		+ "      costPrice\r\n"
		+ "      createdAt\r\n"
		+ "      currency\r\n"
		+ "      deliveryArea\r\n"
		+ "      deliveryType\r\n"
		+ "      description\r\n"
		+ "      id\r\n"
		+ "      isWishlist\r\n"
		+ "      modified\r\n"
		+ "      offerPrice\r\n"
		+ "      productName\r\n"
		+ "      rating\r\n"
		+ "      runningStock\r\n"
		+ "      salesPrice\r\n"
		+ "      service\r\n"
		+ "      sku\r\n"
		+ "      specificatios\r\n"
		+ "      status\r\n"
		+ "      stockQty\r\n"
		+ "      stockStatus\r\n"
		+ "      tags\r\n"
		+ "      totalQna\r\n"
		+ "      totalRating\r\n"
		+ "      totalSold\r\n"
		+ "    }\r\n"
		+ "    rating\r\n"
		+ "    reviewId\r\n"
		+ "    status\r\n"
		+ "    user {\r\n"
		+ "      _id\r\n"
		+ "      about\r\n"
		+ "      adRevenue\r\n"
		+ "      address1\r\n"
		+ "      address2\r\n"
		+ "      admin\r\n"
		+ "      birth_date\r\n"
		+ "      blocked\r\n"
		+ "      blocked_by\r\n"
		+ "      brand\r\n"
		+ "      brand_stars\r\n"
		+ "      content_creator\r\n"
		+ "      contests\r\n"
		+ "      created_at\r\n"
		+ "      creatorFinalScore\r\n"
		+ "      creatorScore\r\n"
		+ "      currency\r\n"
		+ "      diamond_points\r\n"
		+ "      dp\r\n"
		+ "      email\r\n"
		+ "      experience_points\r\n"
		+ "      f_coins\r\n"
		+ "      featured\r\n"
		+ "      firebaseRegToken\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      following\r\n"
		+ "      following_brands\r\n"
		+ "      following_brands_count\r\n"
		+ "      following_count\r\n"
		+ "      gender\r\n"
		+ "      influencer\r\n"
		+ "      invited_by\r\n"
		+ "      isFollow\r\n"
		+ "      isSignupWithGoogle\r\n"
		+ "      lastActivityDate\r\n"
		+ "      lastPurchaseDate\r\n"
		+ "      level\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "      numberOfBrandStars\r\n"
		+ "      numberOfFriends\r\n"
		+ "      postal\r\n"
		+ "      profile_view\r\n"
		+ "      referredBy\r\n"
		+ "      roles\r\n"
		+ "      signUpType\r\n"
		+ "      status\r\n"
		+ "      totalJoinedCampaign\r\n"
		+ "      totalLikedContest\r\n"
		+ "      totalMonetization\r\n"
		+ "      totalReferReg\r\n"
		+ "      totalWatchTimeOfUser\r\n"
		+ "      uniqeVideoViewCountOfUser\r\n"
		+ "      username\r\n"
		+ "      verified\r\n"
		+ "      videos\r\n"
		+ "    }\r\n"
		+ "  }\r\n"
		+ "}";

//46 Fshop>>dashboard>>supportTickets(endIndex: $endIndex, startIndex: $startIndex)  *AUTH
static String supportTicketsQuery = "{\r\n"
		+ "  supportTickets(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    code\r\n"
		+ "    createdAt\r\n"
		+ "    images {\r\n"
		+ "      height\r\n"
		+ "      image\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    issueType\r\n"
		+ "    message\r\n"
		+ "    order {\r\n"
		+ "      _id\r\n"
		+ "      adminPaymentStatus\r\n"
		+ "      codPay\r\n"
		+ "      createdAt\r\n"
		+ "      fcoinDiscount\r\n"
		+ "      note\r\n"
		+ "      onlinePay\r\n"
		+ "      orderId\r\n"
		+ "      orderStatus\r\n"
		+ "      payAfterDiscount\r\n"
		+ "      paymentStatus\r\n"
		+ "      paymentType\r\n"
		+ "      sellerPaymentStatus\r\n"
		+ "      subtotal\r\n"
		+ "      totalAmount\r\n"
		+ "      totalShippingFee\r\n"
		+ "      usedFcoin\r\n"
		+ "      userNote\r\n"
		+ "      voucher\r\n"
		+ "      voucherDiscount\r\n"
		+ "    }\r\n"
		+ "    status\r\n"
		+ "    subject\r\n"
		+ "    updatedAt\r\n"
		+ "    user {\r\n"
		+ "      _id\r\n"
		+ "      about\r\n"
		+ "      adRevenue\r\n"
		+ "      address1\r\n"
		+ "      address2\r\n"
		+ "      admin\r\n"
		+ "      birth_date\r\n"
		+ "      blocked\r\n"
		+ "      blocked_by\r\n"
		+ "      brand\r\n"
		+ "      brand_stars\r\n"
		+ "      content_creator\r\n"
		+ "      contests\r\n"
		+ "      created_at\r\n"
		+ "      creatorFinalScore\r\n"
		+ "      creatorScore\r\n"
		+ "      currency\r\n"
		+ "      diamond_points\r\n"
		+ "      dp\r\n"
		+ "      email\r\n"
		+ "      experience_points\r\n"
		+ "      f_coins\r\n"
		+ "      featured\r\n"
		+ "      firebaseRegToken\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      following\r\n"
		+ "      following_brands\r\n"
		+ "      following_brands_count\r\n"
		+ "      following_count\r\n"
		+ "      gender\r\n"
		+ "      influencer\r\n"
		+ "      invited_by\r\n"
		+ "      isFollow\r\n"
		+ "      isSignupWithGoogle\r\n"
		+ "      lastActivityDate\r\n"
		+ "      lastPurchaseDate\r\n"
		+ "      level\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "      numberOfBrandStars\r\n"
		+ "      numberOfFriends\r\n"
		+ "      postal\r\n"
		+ "      profile_view\r\n"
		+ "      referredBy\r\n"
		+ "      roles\r\n"
		+ "      signUpType\r\n"
		+ "      status\r\n"
		+ "      totalJoinedCampaign\r\n"
		+ "      totalLikedContest\r\n"
		+ "      totalMonetization\r\n"
		+ "      totalReferReg\r\n"
		+ "      totalWatchTimeOfUser\r\n"
		+ "      uniqeVideoViewCountOfUser\r\n"
		+ "      username\r\n"
		+ "      verified\r\n"
		+ "      videos\r\n"
		+ "    }\r\n"
		+ "  }\r\n"
		+ "}";

//47 Fshop>>home>>parentCategories(endIndex: $endIndex, startIndex: $startIndex) 777
static String parentCategoriesQuery = "{\r\n"
		+ "  parentCategories(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    ancestors {\r\n"
		+ "      _id\r\n"
		+ "      name\r\n"
		+ "      slug\r\n"
		+ "      type\r\n"
		+ "    }\r\n"
		+ "    cover\r\n"
		+ "    coverSize {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    createdAt\r\n"
		+ "    description\r\n"
		+ "    hasChild\r\n"
		+ "    icon\r\n"
		+ "    iconSize {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    name\r\n"
		+ "    parent {\r\n"
		+ "      _id\r\n"
		+ "      cover\r\n"
		+ "      createdAt\r\n"
		+ "      description\r\n"
		+ "      hasChild\r\n"
		+ "      icon\r\n"
		+ "      name\r\n"
		+ "      slug\r\n"
		+ "      status\r\n"
		+ "      tags\r\n"
		+ "      totalProduct\r\n"
		+ "      type\r\n"
		+ "      updatedAt\r\n"
		+ "    }\r\n"
		+ "    slug\r\n"
		+ "    status\r\n"
		+ "    tags\r\n"
		+ "    totalProduct\r\n"
		+ "    type\r\n"
		+ "    updatedAt\r\n"
		+ "  }\r\n"
		+ "}";

//48 Fshop>>home>>flashSales(endIndex: $endIndex, startIndex: $startIndex) 777
static String flashSalesQuery = "{\r\n"
		+ "  flashSales(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    discount\r\n"
		+ "    discountPrice\r\n"
		+ "    expireAt\r\n"
		+ "    product {\r\n"
		+ "      _id\r\n"
		+ "      brandName\r\n"
		+ "      category\r\n"
		+ "      costPrice\r\n"
		+ "      createdAt\r\n"
		+ "      currency\r\n"
		+ "      deliveryArea\r\n"
		+ "      deliveryType\r\n"
		+ "      description\r\n"
		+ "      id\r\n"
		+ "      isWishlist\r\n"
		+ "      modified\r\n"
		+ "      offerPrice\r\n"
		+ "      productName\r\n"
		+ "      rating\r\n"
		+ "      runningStock\r\n"
		+ "      salesPrice\r\n"
		+ "      service\r\n"
		+ "      sku\r\n"
		+ "      specificatios\r\n"
		+ "      status\r\n"
		+ "      stockQty\r\n"
		+ "      stockStatus\r\n"
		+ "      tags\r\n"
		+ "      totalQna\r\n"
		+ "      totalRating\r\n"
		+ "      totalSold\r\n"
		+ "    }\r\n"
		+ "    totlaSold\r\n"
		+ "  }\r\n"
		+ "}";

//49 Fshop>>home>>promotionalOffers(offerType: $offerType, pageNumber:$pageNumber, perPage: $perPage) 777
static String promotionalOffersQuery = "{\r\n"
		+ "  promotionalOffers(\r\n"
		+ "    offerType: \"Hot Deals\"\r\n"
		+ "    pageNumber:1\r\n"
		+ "    perPage:1\r\n"
		+ "  ) {\r\n"
		+ "    _id\r\n"
		+ "    areaLimit\r\n"
		+ "    createdAt\r\n"
		+ "    customerLimit\r\n"
		+ "    dailyLimit\r\n"
		+ "    discountType\r\n"
		+ "    discountValue\r\n"
		+ "    endDate\r\n"
		+ "    icon {\r\n"
		+ "      height\r\n"
		+ "      icon\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    name\r\n"
		+ "    offerType\r\n"
		+ "    orderLimit\r\n"
		+ "    products {\r\n"
		+ "      _id\r\n"
		+ "      brandName\r\n"
		+ "      category\r\n"
		+ "      costPrice\r\n"
		+ "      createdAt\r\n"
		+ "      currency\r\n"
		+ "      deliveryArea\r\n"
		+ "      deliveryType\r\n"
		+ "      description\r\n"
		+ "      id\r\n"
		+ "      isWishlist\r\n"
		+ "      modified\r\n"
		+ "      offerPrice\r\n"
		+ "      productName\r\n"
		+ "      rating\r\n"
		+ "      runningStock\r\n"
		+ "      salesPrice\r\n"
		+ "      service\r\n"
		+ "      sku\r\n"
		+ "      specificatios\r\n"
		+ "      status\r\n"
		+ "      stockQty\r\n"
		+ "      stockStatus\r\n"
		+ "      tags\r\n"
		+ "      totalQna\r\n"
		+ "      totalRating\r\n"
		+ "      totalSold\r\n"
		+ "    }\r\n"
		+ "    repeatOrder\r\n"
		+ "    startDate\r\n"
		+ "    status\r\n"
		+ "    type\r\n"
		+ "    updatedAt\r\n"
		+ "  }\r\n"
		+ "}";

//50 Fshop>>home>>topSellingBrands(endIndex: $endIndex, startIndex: $startIndex) 777
static String topSellingBrandsQuery = "{\r\n"
		+ "  topSellingBrands(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    address\r\n"
		+ "    bin\r\n"
		+ "    brandId\r\n"
		+ "    brandUserId\r\n"
		+ "    campaignStartDate\r\n"
		+ "    campaigns\r\n"
		+ "    category\r\n"
		+ "    company_address\r\n"
		+ "    company_name\r\n"
		+ "    contactName\r\n"
		+ "    contact_number\r\n"
		+ "    country\r\n"
		+ "    cover_image\r\n"
		+ "    cover_image_size {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    description\r\n"
		+ "    diamond_points\r\n"
		+ "    email\r\n"
		+ "    f_coins\r\n"
		+ "    followers\r\n"
		+ "    followers_count\r\n"
		+ "    hashtag\r\n"
		+ "    is_follow\r\n"
		+ "    is_master\r\n"
		+ "    manager {\r\n"
		+ "      email\r\n"
		+ "    }\r\n"
		+ "    maxDeliveryTime\r\n"
		+ "    minDeliveryTime\r\n"
		+ "    modified\r\n"
		+ "    name\r\n"
		+ "    nid\r\n"
		+ "    preferedBrandtags\r\n"
		+ "    preferedHashtags\r\n"
		+ "    profile_picture\r\n"
		+ "    profile_picture_size {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    published\r\n"
		+ "    referer {\r\n"
		+ "      _id\r\n"
		+ "      dp\r\n"
		+ "      name\r\n"
		+ "    }\r\n"
		+ "    social\r\n"
		+ "    star_count\r\n"
		+ "    stars {\r\n"
		+ "      _id\r\n"
		+ "      about\r\n"
		+ "      adRevenue\r\n"
		+ "      address1\r\n"
		+ "      address2\r\n"
		+ "      admin\r\n"
		+ "      birth_date\r\n"
		+ "      blocked\r\n"
		+ "      blocked_by\r\n"
		+ "      brand\r\n"
		+ "      brand_stars\r\n"
		+ "      content_creator\r\n"
		+ "      contests\r\n"
		+ "      created_at\r\n"
		+ "      creatorFinalScore\r\n"
		+ "      creatorScore\r\n"
		+ "      currency\r\n"
		+ "      diamond_points\r\n"
		+ "      dp\r\n"
		+ "      email\r\n"
		+ "      experience_points\r\n"
		+ "      f_coins\r\n"
		+ "      featured\r\n"
		+ "      firebaseRegToken\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      following\r\n"
		+ "      following_brands\r\n"
		+ "      following_brands_count\r\n"
		+ "      following_count\r\n"
		+ "      gender\r\n"
		+ "      influencer\r\n"
		+ "      invited_by\r\n"
		+ "      isFollow\r\n"
		+ "      isSignupWithGoogle\r\n"
		+ "      lastActivityDate\r\n"
		+ "      lastPurchaseDate\r\n"
		+ "      level\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "      numberOfBrandStars\r\n"
		+ "      numberOfFriends\r\n"
		+ "      postal\r\n"
		+ "      profile_view\r\n"
		+ "      referredBy\r\n"
		+ "      roles\r\n"
		+ "      signUpType\r\n"
		+ "      status\r\n"
		+ "      totalJoinedCampaign\r\n"
		+ "      totalLikedContest\r\n"
		+ "      totalMonetization\r\n"
		+ "      totalReferReg\r\n"
		+ "      totalWatchTimeOfUser\r\n"
		+ "      uniqeVideoViewCountOfUser\r\n"
		+ "      username\r\n"
		+ "      verified\r\n"
		+ "      videos\r\n"
		+ "    }\r\n"
		+ "    tin\r\n"
		+ "    type\r\n"
		+ "    url\r\n"
		+ "    varifiedEmail\r\n"
		+ "    varifyStatus\r\n"
		+ "    website\r\n"
		+ "  }\r\n"
		+ "}";

//51 Fshop>>home>>productsByCategory(endIndex: $endIndex, startIndex: $startIndex, categoryId: $categoryId) SEQUENCES OF TESTS
static String productsByCategoryQuery = "";
//51 Query Function ⚡
static public String productsByCategoryQueryMaker(String input) {
	productsByCategoryQuery = "{\r\n"
			+ "  productsByCategory(\r\n"
			+ "    categoryId: \""+input+"\"\r\n"
			+ "    endIndex: 10\r\n"
			+ "    startIndex: 1\r\n"
			+ "  ) {\r\n"
			+ "    _id\r\n"
			+ "    brand {\r\n"
			+ "      _id\r\n"
			+ "      brandtag\r\n"
			+ "      name\r\n"
			+ "      profile_picture\r\n"
			+ "    }\r\n"
			+ "    brandName\r\n"
			+ "    category\r\n"
			+ "    costPrice\r\n"
			+ "    createdAt\r\n"
			+ "    currency\r\n"
			+ "    deliveryArea\r\n"
			+ "    deliveryType\r\n"
			+ "    description\r\n"
			+ "    id\r\n"
			+ "    images {\r\n"
			+ "      color\r\n"
			+ "      height\r\n"
			+ "      image\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    isWishlist\r\n"
			+ "    modified\r\n"
			+ "    offerPrice\r\n"
			+ "    productName\r\n"
			+ "    promotionalOffers {\r\n"
			+ "      _id\r\n"
			+ "      areaLimit\r\n"
			+ "      createdAt\r\n"
			+ "      customerLimit\r\n"
			+ "      dailyLimit\r\n"
			+ "      discountType\r\n"
			+ "      discountValue\r\n"
			+ "      endDate\r\n"
			+ "      name\r\n"
			+ "      offerType\r\n"
			+ "      orderLimit\r\n"
			+ "      repeatOrder\r\n"
			+ "      startDate\r\n"
			+ "      status\r\n"
			+ "      type\r\n"
			+ "      updatedAt\r\n"
			+ "    }\r\n"
			+ "    rating\r\n"
			+ "    runningStock\r\n"
			+ "    salesPrice\r\n"
			+ "    seller {\r\n"
			+ "      _id\r\n"
			+ "      address\r\n"
			+ "      bin\r\n"
			+ "      brandId\r\n"
			+ "      brandUserId\r\n"
			+ "      campaignStartDate\r\n"
			+ "      campaigns\r\n"
			+ "      category\r\n"
			+ "      company_address\r\n"
			+ "      company_name\r\n"
			+ "      contactName\r\n"
			+ "      contact_number\r\n"
			+ "      country\r\n"
			+ "      cover_image\r\n"
			+ "      description\r\n"
			+ "      diamond_points\r\n"
			+ "      email\r\n"
			+ "      f_coins\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      hashtag\r\n"
			+ "      is_follow\r\n"
			+ "      is_master\r\n"
			+ "      maxDeliveryTime\r\n"
			+ "      minDeliveryTime\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      nid\r\n"
			+ "      preferedBrandtags\r\n"
			+ "      preferedHashtags\r\n"
			+ "      profile_picture\r\n"
			+ "      published\r\n"
			+ "      social\r\n"
			+ "      star_count\r\n"
			+ "      tin\r\n"
			+ "      type\r\n"
			+ "      url\r\n"
			+ "      varifiedEmail\r\n"
			+ "      varifyStatus\r\n"
			+ "      website\r\n"
			+ "    }\r\n"
			+ "    service\r\n"
			+ "    sku\r\n"
			+ "    specificatios\r\n"
			+ "    status\r\n"
			+ "    stockQty\r\n"
			+ "    stockStatus\r\n"
			+ "    tags\r\n"
			+ "    totalQna\r\n"
			+ "    totalRating\r\n"
			+ "    totalSold\r\n"
			+ "  }\r\n"
			+ "}";
	return productsByCategoryQuery;
}

//52 Fshop>>home>>mainBanners(endIndex: $endIndex, startIndex: $startIndex) 777
static String mainBannersQuery = "{\r\n"
		+ "  mainBanners(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    banner\r\n"
		+ "    bannerSize {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    createdAt\r\n"
		+ "    description\r\n"
		+ "    filterKey\r\n"
		+ "    filterValue\r\n"
		+ "    position\r\n"
		+ "    products {\r\n"
		+ "      _id\r\n"
		+ "      brandName\r\n"
		+ "      category\r\n"
		+ "      costPrice\r\n"
		+ "      createdAt\r\n"
		+ "      currency\r\n"
		+ "      deliveryArea\r\n"
		+ "      deliveryType\r\n"
		+ "      description\r\n"
		+ "      id\r\n"
		+ "      isWishlist\r\n"
		+ "      modified\r\n"
		+ "      offerPrice\r\n"
		+ "      productName\r\n"
		+ "      rating\r\n"
		+ "      runningStock\r\n"
		+ "      salesPrice\r\n"
		+ "      service\r\n"
		+ "      sku\r\n"
		+ "      specificatios\r\n"
		+ "      status\r\n"
		+ "      stockQty\r\n"
		+ "      stockStatus\r\n"
		+ "      tags\r\n"
		+ "      totalQna\r\n"
		+ "      totalRating\r\n"
		+ "      totalSold\r\n"
		+ "    }\r\n"
		+ "    status\r\n"
		+ "    updatedAt\r\n"
		+ "    withProduct\r\n"
		+ "  }\r\n"
		+ "}";

//53 Fshop>>home>>offerBanners(endIndex: $endIndex, startIndex: $startIndex) 777
static String offerBannersQuery = "{\r\n"
		+ "  offerBanners(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    banner\r\n"
		+ "    bannerSize {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    createdAt\r\n"
		+ "    description\r\n"
		+ "    filterKey\r\n"
		+ "    filterValue\r\n"
		+ "    position\r\n"
		+ "    products {\r\n"
		+ "      _id\r\n"
		+ "      brandName\r\n"
		+ "      category\r\n"
		+ "      costPrice\r\n"
		+ "      createdAt\r\n"
		+ "      currency\r\n"
		+ "      deliveryArea\r\n"
		+ "      deliveryType\r\n"
		+ "      description\r\n"
		+ "      id\r\n"
		+ "      isWishlist\r\n"
		+ "      modified\r\n"
		+ "      offerPrice\r\n"
		+ "      productName\r\n"
		+ "      rating\r\n"
		+ "      runningStock\r\n"
		+ "      salesPrice\r\n"
		+ "      service\r\n"
		+ "      sku\r\n"
		+ "      specificatios\r\n"
		+ "      status\r\n"
		+ "      stockQty\r\n"
		+ "      stockStatus\r\n"
		+ "      tags\r\n"
		+ "      totalQna\r\n"
		+ "      totalRating\r\n"
		+ "      totalSold\r\n"
		+ "    }\r\n"
		+ "    status\r\n"
		+ "    updatedAt\r\n"
		+ "    withProduct\r\n"
		+ "  }\r\n"
		+ "}";

//54 Fshop>>home>>categoryChildrens(parentId: $parentId) SEQUENCES OF TESTS
static String categoryChildrensQuery = "";
//54 Query Function ⚡
static public String categoryChildrensQueryMaker(String input) {
	categoryChildrensQuery = "{\r\n"
			+ "  categoryChildrens(parentId: \""+input+"\") {\r\n"
			+ "    _id\r\n"
			+ "    ancestors {\r\n"
			+ "      _id\r\n"
			+ "      name\r\n"
			+ "      slug\r\n"
			+ "      type\r\n"
			+ "    }\r\n"
			+ "    createdAt\r\n"
			+ "    description\r\n"
			+ "    hasChild\r\n"
			+ "    name\r\n"
			+ "    slug\r\n"
			+ "    status\r\n"
			+ "    tags\r\n"
			+ "    totalProduct\r\n"
			+ "    type\r\n"
			+ "    updatedAt\r\n"
			+ "  }\r\n"
			+ "}";
	return categoryChildrensQuery;
}

//55 Fshop>>home>>filterHotdeals(hotDealFilterInput: \$hotDealFilterInput) SEQUENCES OF TESTS
static String filterHotdealsQuery = "{\r\n"
		+ "  filterHotdeals(hotDealFilterInput: {}) {\r\n"
		+ "    _id\r\n"
		+ "    brand {\r\n"
		+ "      _id\r\n"
		+ "      brandtag\r\n"
		+ "      name\r\n"
		+ "      profile_picture\r\n"
		+ "    }\r\n"
		+ "    brandName\r\n"
		+ "    category\r\n"
		+ "    costPrice\r\n"
		+ "    createdAt\r\n"
		+ "    currency\r\n"
		+ "    deliveryArea\r\n"
		+ "    deliveryType\r\n"
		+ "    description\r\n"
		+ "    modified\r\n"
		+ "    offerPrice\r\n"
		+ "    productName\r\n"
		+ "    promotionalOffers {\r\n"
		+ "      _id\r\n"
		+ "      discountType\r\n"
		+ "      discountValue\r\n"
		+ "      status\r\n"
		+ "    }\r\n"
		+ "    rating\r\n"
		+ "    runningStock\r\n"
		+ "    salesPrice\r\n"
		+ "    service\r\n"
		+ "    sku\r\n"
		+ "    specificatios\r\n"
		+ "    status\r\n"
		+ "    stockQty\r\n"
		+ "    stockStatus\r\n"
		+ "    tags\r\n"
		+ "    totalQna\r\n"
		+ "    totalRating\r\n"
		+ "    totalSold\r\n"
		+ "  }\r\n"
		+ "}";

//56 Fshop>>home>>bannerProducts(bannerId: $bannerId, pageNumber: $pageNumber, perPage: $perPage) SEQUENCES OF TESTS
static String bannerProductsQuery = "";
//56 Query Function ⚡
static public String bannerProductsQueryMaker(String input) {
	bannerProductsQuery = "{\r\n"
			+ "  bannerProducts(bannerId: \""+input+"\", pageNumber: 1, perPage: 1) {\r\n"
			+ "    _id\r\n"
			+ "    brand {\r\n"
			+ "      _id\r\n"
			+ "      brandtag\r\n"
			+ "      name\r\n"
			+ "      profile_picture\r\n"
			+ "    }\r\n"
			+ "    brandName\r\n"
			+ "    category\r\n"
			+ "    costPrice\r\n"
			+ "    createdAt\r\n"
			+ "    currency\r\n"
			+ "    deliveryArea\r\n"
			+ "    deliveryType\r\n"
			+ "    description\r\n"
			+ "    id\r\n"
			+ "    images {\r\n"
			+ "      color\r\n"
			+ "      height\r\n"
			+ "      image\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    isWishlist\r\n"
			+ "    modified\r\n"
			+ "    offerPrice\r\n"
			+ "    productName\r\n"
			+ "    promotionalOffers {\r\n"
			+ "      _id\r\n"
			+ "      areaLimit\r\n"
			+ "      createdAt\r\n"
			+ "      customerLimit\r\n"
			+ "      dailyLimit\r\n"
			+ "      discountType\r\n"
			+ "      discountValue\r\n"
			+ "      endDate\r\n"
			+ "      name\r\n"
			+ "      offerType\r\n"
			+ "      orderLimit\r\n"
			+ "      repeatOrder\r\n"
			+ "      startDate\r\n"
			+ "      status\r\n"
			+ "      type\r\n"
			+ "      updatedAt\r\n"
			+ "    }\r\n"
			+ "    rating\r\n"
			+ "    runningStock\r\n"
			+ "    salesPrice\r\n"
			+ "    service\r\n"
			+ "    sku\r\n"
			+ "    specificatios\r\n"
			+ "    status\r\n"
			+ "    stockQty\r\n"
			+ "    stockStatus\r\n"
			+ "    tags\r\n"
			+ "    totalQna\r\n"
			+ "    totalRating\r\n"
			+ "    totalSold\r\n"
			+ "  }\r\n"
			+ "}";
	return bannerProductsQuery;
}

//57 Fshop>>order>>ordersByUser   *AUTH
static String ordersByUserQuery = "{\r\n"
		+ "  ordersByUser {\r\n"
		+ "    _id\r\n"
		+ "    adminPaymentStatus\r\n"
		+ "    billingAddress {\r\n"
		+ "      _id\r\n"
		+ "      area\r\n"
		+ "      contactNumber\r\n"
		+ "      country\r\n"
		+ "      district\r\n"
		+ "      email\r\n"
		+ "      name\r\n"
		+ "      policeStation\r\n"
		+ "      postCode\r\n"
		+ "      village\r\n"
		+ "    }\r\n"
		+ "    codPay\r\n"
		+ "    createdAt\r\n"
		+ "    fcoinDiscount\r\n"
		+ "    note\r\n"
		+ "    onlinePay\r\n"
		+ "    orderId\r\n"
		+ "    orderStatus\r\n"
		+ "    packages {\r\n"
		+ "      deliveryAmount\r\n"
		+ "      id\r\n"
		+ "      status\r\n"
		+ "      total\r\n"
		+ "    }\r\n"
		+ "    payAfterDiscount\r\n"
		+ "    paymentStatus\r\n"
		+ "    paymentType\r\n"
		+ "    sellerPaymentStatus\r\n"
		+ "    shippingAddress {\r\n"
		+ "      _id\r\n"
		+ "      area\r\n"
		+ "      contactNumber\r\n"
		+ "      country\r\n"
		+ "      district\r\n"
		+ "      email\r\n"
		+ "      name\r\n"
		+ "      policeStation\r\n"
		+ "      postCode\r\n"
		+ "      village\r\n"
		+ "    }\r\n"
		+ "    subtotal\r\n"
		+ "    totalAmount\r\n"
		+ "    totalShippingFee\r\n"
		+ "    updatedBy {\r\n"
		+ "      _id\r\n"
		+ "      about\r\n"
		+ "      adRevenue\r\n"
		+ "      address1\r\n"
		+ "      address2\r\n"
		+ "      admin\r\n"
		+ "      birth_date\r\n"
		+ "      blocked\r\n"
		+ "      blocked_by\r\n"
		+ "      brand\r\n"
		+ "      brand_stars\r\n"
		+ "      content_creator\r\n"
		+ "      contests\r\n"
		+ "      created_at\r\n"
		+ "      creatorFinalScore\r\n"
		+ "      creatorScore\r\n"
		+ "      currency\r\n"
		+ "      diamond_points\r\n"
		+ "      dp\r\n"
		+ "      email\r\n"
		+ "      experience_points\r\n"
		+ "      f_coins\r\n"
		+ "      featured\r\n"
		+ "      firebaseRegToken\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      following\r\n"
		+ "      following_brands\r\n"
		+ "      following_brands_count\r\n"
		+ "      following_count\r\n"
		+ "      gender\r\n"
		+ "      influencer\r\n"
		+ "      invited_by\r\n"
		+ "      isFollow\r\n"
		+ "      lastActivityDate\r\n"
		+ "      lastPurchaseDate\r\n"
		+ "      level\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "      numberOfBrandStars\r\n"
		+ "      numberOfFriends\r\n"
		+ "      postal\r\n"
		+ "      profile_view\r\n"
		+ "      referredBy\r\n"
		+ "      roles\r\n"
		+ "      signUpType\r\n"
		+ "      status\r\n"
		+ "      totalJoinedCampaign\r\n"
		+ "      totalLikedContest\r\n"
		+ "      totalMonetization\r\n"
		+ "      totalReferReg\r\n"
		+ "      totalWatchTimeOfUser\r\n"
		+ "      uniqeVideoViewCountOfUser\r\n"
		+ "      username\r\n"
		+ "      verified\r\n"
		+ "      videos\r\n"
		+ "    }\r\n"
		+ "    usedFcoin\r\n"
		+ "    user {\r\n"
		+ "      _id\r\n"
		+ "      about\r\n"
		+ "      adRevenue\r\n"
		+ "      address1\r\n"
		+ "      address2\r\n"
		+ "      admin\r\n"
		+ "      birth_date\r\n"
		+ "      blocked\r\n"
		+ "      blocked_by\r\n"
		+ "      brand\r\n"
		+ "      brand_stars\r\n"
		+ "      content_creator\r\n"
		+ "      contests\r\n"
		+ "      created_at\r\n"
		+ "      creatorFinalScore\r\n"
		+ "      creatorScore\r\n"
		+ "      currency\r\n"
		+ "      diamond_points\r\n"
		+ "      dp\r\n"
		+ "      email\r\n"
		+ "      experience_points\r\n"
		+ "      f_coins\r\n"
		+ "      featured\r\n"
		+ "      firebaseRegToken\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      following\r\n"
		+ "      following_brands\r\n"
		+ "      following_brands_count\r\n"
		+ "      following_count\r\n"
		+ "      gender\r\n"
		+ "      influencer\r\n"
		+ "      invited_by\r\n"
		+ "      isFollow\r\n"
		+ "      lastActivityDate\r\n"
		+ "      lastPurchaseDate\r\n"
		+ "      level\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "      numberOfBrandStars\r\n"
		+ "      numberOfFriends\r\n"
		+ "      postal\r\n"
		+ "      profile_view\r\n"
		+ "      referredBy\r\n"
		+ "      roles\r\n"
		+ "      signUpType\r\n"
		+ "      status\r\n"
		+ "      totalJoinedCampaign\r\n"
		+ "      totalLikedContest\r\n"
		+ "      totalMonetization\r\n"
		+ "      totalReferReg\r\n"
		+ "      totalWatchTimeOfUser\r\n"
		+ "      uniqeVideoViewCountOfUser\r\n"
		+ "      username\r\n"
		+ "      verified\r\n"
		+ "      videos\r\n"
		+ "    }\r\n"
		+ "    voucher\r\n"
		+ "    voucherDiscount\r\n"
		+ "  }\r\n"
		+ "}";

//58 Fshop>>product>>product(id: $productId) SEQUENCES OF TESTS
static String productByIdQuery = "";
//58 Query Function ⚡
static public String productByIdQueryMaker(String input) {
	productByIdQuery = "{\r\n"
			+ "  product(id: \""+input+"\") {\r\n"
			+ "    _id\r\n"
			+ "    brand {\r\n"
			+ "      _id\r\n"
			+ "      brandtag\r\n"
			+ "      name\r\n"
			+ "      profile_picture\r\n"
			+ "    }\r\n"
			+ "    brandName\r\n"
			+ "    category\r\n"
			+ "    costPrice\r\n"
			+ "    createdAt\r\n"
			+ "    currency\r\n"
			+ "    deliveryArea\r\n"
			+ "    deliveryType\r\n"
			+ "    description\r\n"
			+ "    id\r\n"
			+ "    images {\r\n"
			+ "      color\r\n"
			+ "      height\r\n"
			+ "      image\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    isWishlist\r\n"
			+ "    modified\r\n"
			+ "    offerPrice\r\n"
			+ "    productName\r\n"
			+ "    promotionalOffers {\r\n"
			+ "      _id\r\n"
			+ "      areaLimit\r\n"
			+ "      createdAt\r\n"
			+ "      customerLimit\r\n"
			+ "      dailyLimit\r\n"
			+ "      discountType\r\n"
			+ "      discountValue\r\n"
			+ "      endDate\r\n"
			+ "      name\r\n"
			+ "      offerType\r\n"
			+ "      orderLimit\r\n"
			+ "      repeatOrder\r\n"
			+ "      startDate\r\n"
			+ "      status\r\n"
			+ "      type\r\n"
			+ "      updatedAt\r\n"
			+ "    }\r\n"
			+ "    rating\r\n"
			+ "    runningStock\r\n"
			+ "    salesPrice\r\n"
			+ "    seller {\r\n"
			+ "      _id\r\n"
			+ "      address\r\n"
			+ "      bin\r\n"
			+ "      brandId\r\n"
			+ "      brandUserId\r\n"
			+ "      campaignStartDate\r\n"
			+ "      campaigns\r\n"
			+ "      category\r\n"
			+ "      company_address\r\n"
			+ "      company_name\r\n"
			+ "      contactName\r\n"
			+ "      contact_number\r\n"
			+ "      country\r\n"
			+ "      cover_image\r\n"
			+ "      description\r\n"
			+ "      diamond_points\r\n"
			+ "      email\r\n"
			+ "      f_coins\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      hashtag\r\n"
			+ "      is_follow\r\n"
			+ "      is_master\r\n"
			+ "      maxDeliveryTime\r\n"
			+ "      minDeliveryTime\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      nid\r\n"
			+ "      preferedBrandtags\r\n"
			+ "      preferedHashtags\r\n"
			+ "      profile_picture\r\n"
			+ "      published\r\n"
			+ "      social\r\n"
			+ "      star_count\r\n"
			+ "      tin\r\n"
			+ "      type\r\n"
			+ "      url\r\n"
			+ "      varifiedEmail\r\n"
			+ "      varifyStatus\r\n"
			+ "      website\r\n"
			+ "    }\r\n"
			+ "    service\r\n"
			+ "    sku\r\n"
			+ "    specificatios\r\n"
			+ "    status\r\n"
			+ "    stockQty\r\n"
			+ "    stockStatus\r\n"
			+ "    tags\r\n"
			+ "    totalQna\r\n"
			+ "    totalRating\r\n"
			+ "    totalSold\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";
	return productByIdQuery;
}

//59 Fshop>>product>>productFaqs(endIndex: $endIndex, productId: $productId, startIndex: $startIndex) SEQUENCES OF TESTS
static String productFaqsByIdQuery ="";
//59 Query Function ⚡
static public String productFaqsByIdQueryMaker(String input) {
	productFaqsByIdQuery = "{\r\n"
			+ "  productFaqs(endIndex: 10, productId: \""+input+"\", startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    answers {\r\n"
			+ "      ans\r\n"
			+ "      createdAt\r\n"
			+ "    }\r\n"
			+ "    createdAt\r\n"
			+ "    id\r\n"
			+ "    product {\r\n"
			+ "      _id\r\n"
			+ "      brandName\r\n"
			+ "      category\r\n"
			+ "      costPrice\r\n"
			+ "      createdAt\r\n"
			+ "      currency\r\n"
			+ "      deliveryArea\r\n"
			+ "      deliveryType\r\n"
			+ "      description\r\n"
			+ "      id\r\n"
			+ "      isWishlist\r\n"
			+ "      modified\r\n"
			+ "      offerPrice\r\n"
			+ "      productName\r\n"
			+ "      rating\r\n"
			+ "      runningStock\r\n"
			+ "      salesPrice\r\n"
			+ "      service\r\n"
			+ "      sku\r\n"
			+ "      specificatios\r\n"
			+ "      status\r\n"
			+ "      stockQty\r\n"
			+ "      stockStatus\r\n"
			+ "      tags\r\n"
			+ "      totalQna\r\n"
			+ "      totalRating\r\n"
			+ "      totalSold\r\n"
			+ "    }\r\n"
			+ "    question\r\n"
			+ "    status\r\n"
			+ "    updatedAt\r\n"
			+ "    user {\r\n"
			+ "      _id\r\n"
			+ "      about\r\n"
			+ "      adRevenue\r\n"
			+ "      address1\r\n"
			+ "      address2\r\n"
			+ "      admin\r\n"
			+ "      birth_date\r\n"
			+ "      blocked\r\n"
			+ "      blocked_by\r\n"
			+ "      brand\r\n"
			+ "      brand_stars\r\n"
			+ "      content_creator\r\n"
			+ "      contests\r\n"
			+ "      created_at\r\n"
			+ "      creatorFinalScore\r\n"
			+ "      creatorScore\r\n"
			+ "      currency\r\n"
			+ "      diamond_points\r\n"
			+ "      dp\r\n"
			+ "      email\r\n"
			+ "      experience_points\r\n"
			+ "      f_coins\r\n"
			+ "      featured\r\n"
			+ "      firebaseRegToken\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      following\r\n"
			+ "      following_brands\r\n"
			+ "      following_brands_count\r\n"
			+ "      following_count\r\n"
			+ "      gender\r\n"
			+ "      influencer\r\n"
			+ "      invited_by\r\n"
			+ "      isFollow\r\n"
			+ "      isSignupWithGoogle\r\n"
			+ "      lastActivityDate\r\n"
			+ "      lastPurchaseDate\r\n"
			+ "      level\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      numberOfBrandStars\r\n"
			+ "      numberOfFriends\r\n"
			+ "      postal\r\n"
			+ "      profile_view\r\n"
			+ "      referredBy\r\n"
			+ "      roles\r\n"
			+ "      signUpType\r\n"
			+ "      status\r\n"
			+ "      totalJoinedCampaign\r\n"
			+ "      totalLikedContest\r\n"
			+ "      totalMonetization\r\n"
			+ "      totalReferReg\r\n"
			+ "      totalWatchTimeOfUser\r\n"
			+ "      uniqeVideoViewCountOfUser\r\n"
			+ "      username\r\n"
			+ "      verified\r\n"
			+ "      videos\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return productFaqsByIdQuery;
}

//60 Fshop>>product>>productReview(endIndex: $endIndex, productId: $productId, startIndex: $startIndex) SEQUENCES OF TESTS
static String productReviewQuery = "";
//60 Query Function ⚡
static public String productReviewQueryMaker(String input) {
	productByIdQuery = "{\r\n"
			+ "  productReview(endIndex: 10, productId: \""+input+"\", startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    createdAt\r\n"
			+ "    description\r\n"
			+ "    images {\r\n"
			+ "      height\r\n"
			+ "      image\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    product {\r\n"
			+ "      _id\r\n"
			+ "      brandName\r\n"
			+ "      category\r\n"
			+ "      costPrice\r\n"
			+ "      createdAt\r\n"
			+ "      currency\r\n"
			+ "      deliveryArea\r\n"
			+ "      deliveryType\r\n"
			+ "      description\r\n"
			+ "      id\r\n"
			+ "      isWishlist\r\n"
			+ "      modified\r\n"
			+ "      offerPrice\r\n"
			+ "      productName\r\n"
			+ "      rating\r\n"
			+ "      runningStock\r\n"
			+ "      salesPrice\r\n"
			+ "      service\r\n"
			+ "      sku\r\n"
			+ "      specificatios\r\n"
			+ "      status\r\n"
			+ "      stockQty\r\n"
			+ "      stockStatus\r\n"
			+ "      tags\r\n"
			+ "      totalQna\r\n"
			+ "      totalRating\r\n"
			+ "      totalSold\r\n"
			+ "    }\r\n"
			+ "    rating\r\n"
			+ "    reviewId\r\n"
			+ "    status\r\n"
			+ "    user {\r\n"
			+ "      _id\r\n"
			+ "      about\r\n"
			+ "      adRevenue\r\n"
			+ "      address1\r\n"
			+ "      address2\r\n"
			+ "      admin\r\n"
			+ "      birth_date\r\n"
			+ "      blocked\r\n"
			+ "      blocked_by\r\n"
			+ "      brand\r\n"
			+ "      brand_stars\r\n"
			+ "      content_creator\r\n"
			+ "      contests\r\n"
			+ "      created_at\r\n"
			+ "      creatorFinalScore\r\n"
			+ "      creatorScore\r\n"
			+ "      currency\r\n"
			+ "      diamond_points\r\n"
			+ "      dp\r\n"
			+ "      email\r\n"
			+ "      experience_points\r\n"
			+ "      f_coins\r\n"
			+ "      featured\r\n"
			+ "      firebaseRegToken\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      following\r\n"
			+ "      following_brands\r\n"
			+ "      following_brands_count\r\n"
			+ "      following_count\r\n"
			+ "      gender\r\n"
			+ "      influencer\r\n"
			+ "      invited_by\r\n"
			+ "      isFollow\r\n"
			+ "      isSignupWithGoogle\r\n"
			+ "      lastActivityDate\r\n"
			+ "      lastPurchaseDate\r\n"
			+ "      level\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      numberOfBrandStars\r\n"
			+ "      numberOfFriends\r\n"
			+ "      postal\r\n"
			+ "      profile_view\r\n"
			+ "      referredBy\r\n"
			+ "      roles\r\n"
			+ "      signUpType\r\n"
			+ "      status\r\n"
			+ "      totalJoinedCampaign\r\n"
			+ "      totalLikedContest\r\n"
			+ "      totalMonetization\r\n"
			+ "      totalReferReg\r\n"
			+ "      totalWatchTimeOfUser\r\n"
			+ "      uniqeVideoViewCountOfUser\r\n"
			+ "      username\r\n"
			+ "      verified\r\n"
			+ "      videos\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";
	return productByIdQuery;
}

//61 Fshop>>search>>searchProduct(endIndex: $endIndex, query: $query, startIndex: $startIndex) 404
static String searchProductQuery = "";
//61 Query Function ⚡
static public String searchProductQueryMaker(String input) {
	searchProductQuery = "{\r\n"
			+ "  searchProduct(endIndex: 10, query: \""+input+"\", startIndex: 1) {\r\n"
			+ "    _id\r\n"
			+ "    brand {\r\n"
			+ "      _id\r\n"
			+ "      brandtag\r\n"
			+ "      name\r\n"
			+ "      profile_picture\r\n"
			+ "    }\r\n"
			+ "    brandName\r\n"
			+ "    category\r\n"
			+ "    costPrice\r\n"
			+ "    createdAt\r\n"
			+ "    currency\r\n"
			+ "    deliveryArea\r\n"
			+ "    deliveryType\r\n"
			+ "    description\r\n"
			+ "    id\r\n"
			+ "    images {\r\n"
			+ "      color\r\n"
			+ "      height\r\n"
			+ "      image\r\n"
			+ "      size\r\n"
			+ "      width\r\n"
			+ "    }\r\n"
			+ "    isWishlist\r\n"
			+ "    modified\r\n"
			+ "    offerPrice\r\n"
			+ "    productName\r\n"
			+ "    promotionalOffers {\r\n"
			+ "      _id\r\n"
			+ "      areaLimit\r\n"
			+ "      createdAt\r\n"
			+ "      customerLimit\r\n"
			+ "      dailyLimit\r\n"
			+ "      discountType\r\n"
			+ "      discountValue\r\n"
			+ "      endDate\r\n"
			+ "      name\r\n"
			+ "      offerType\r\n"
			+ "      orderLimit\r\n"
			+ "      repeatOrder\r\n"
			+ "      startDate\r\n"
			+ "      status\r\n"
			+ "      type\r\n"
			+ "      updatedAt\r\n"
			+ "    }\r\n"
			+ "    rating\r\n"
			+ "    runningStock\r\n"
			+ "    salesPrice\r\n"
			+ "    seller {\r\n"
			+ "      _id\r\n"
			+ "      address\r\n"
			+ "      bin\r\n"
			+ "      brandId\r\n"
			+ "      brandUserId\r\n"
			+ "      campaignStartDate\r\n"
			+ "      campaigns\r\n"
			+ "      category\r\n"
			+ "      company_address\r\n"
			+ "      company_name\r\n"
			+ "      contactName\r\n"
			+ "      contact_number\r\n"
			+ "      country\r\n"
			+ "      cover_image\r\n"
			+ "      description\r\n"
			+ "      diamond_points\r\n"
			+ "      email\r\n"
			+ "      f_coins\r\n"
			+ "      followers\r\n"
			+ "      followers_count\r\n"
			+ "      hashtag\r\n"
			+ "      is_follow\r\n"
			+ "      is_master\r\n"
			+ "      maxDeliveryTime\r\n"
			+ "      minDeliveryTime\r\n"
			+ "      modified\r\n"
			+ "      name\r\n"
			+ "      nid\r\n"
			+ "      preferedBrandtags\r\n"
			+ "      preferedHashtags\r\n"
			+ "      profile_picture\r\n"
			+ "      published\r\n"
			+ "      social\r\n"
			+ "      star_count\r\n"
			+ "      tin\r\n"
			+ "      type\r\n"
			+ "      url\r\n"
			+ "      varifiedEmail\r\n"
			+ "      varifyStatus\r\n"
			+ "      website\r\n"
			+ "    }\r\n"
			+ "    service\r\n"
			+ "    sku\r\n"
			+ "    specificatios\r\n"
			+ "    status\r\n"
			+ "    stockQty\r\n"
			+ "    stockStatus\r\n"
			+ "    tags\r\n"
			+ "    totalQna\r\n"
			+ "    totalRating\r\n"
			+ "    totalSold\r\n"
			+ "  }\r\n"
			+ "}";
	return searchProductQuery;
}

//62 Fshop>>wishList>>wishlistProducts(endIndex: $endIndex, startIndex: $startIndex) *AUTH
static String wishlistProductsQuery = "{\r\n"
		+ "  wishlistProducts(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    brand {\r\n"
		+ "      _id\r\n"
		+ "      brandtag\r\n"
		+ "      name\r\n"
		+ "      profile_picture\r\n"
		+ "    }\r\n"
		+ "    brandName\r\n"
		+ "    category\r\n"
		+ "    costPrice\r\n"
		+ "    createdAt\r\n"
		+ "    currency\r\n"
		+ "    deliveryArea\r\n"
		+ "    deliveryType\r\n"
		+ "    description\r\n"
		+ "    id\r\n"
		+ "    images {\r\n"
		+ "      color\r\n"
		+ "      height\r\n"
		+ "      image\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    isWishlist\r\n"
		+ "    modified\r\n"
		+ "    offerPrice\r\n"
		+ "    productName\r\n"
		+ "    promotionalOffers {\r\n"
		+ "      _id\r\n"
		+ "      areaLimit\r\n"
		+ "      createdAt\r\n"
		+ "      customerLimit\r\n"
		+ "      dailyLimit\r\n"
		+ "      discountType\r\n"
		+ "      discountValue\r\n"
		+ "      endDate\r\n"
		+ "      name\r\n"
		+ "      offerType\r\n"
		+ "      orderLimit\r\n"
		+ "      repeatOrder\r\n"
		+ "      startDate\r\n"
		+ "      status\r\n"
		+ "      type\r\n"
		+ "      updatedAt\r\n"
		+ "    }\r\n"
		+ "    rating\r\n"
		+ "    runningStock\r\n"
		+ "    salesPrice\r\n"
		+ "    seller {\r\n"
		+ "      _id\r\n"
		+ "      address\r\n"
		+ "      bin\r\n"
		+ "      brandId\r\n"
		+ "      brandUserId\r\n"
		+ "      campaignStartDate\r\n"
		+ "      campaigns\r\n"
		+ "      category\r\n"
		+ "      company_address\r\n"
		+ "      company_name\r\n"
		+ "      contactName\r\n"
		+ "      contact_number\r\n"
		+ "      country\r\n"
		+ "      cover_image\r\n"
		+ "      description\r\n"
		+ "      diamond_points\r\n"
		+ "      email\r\n"
		+ "      f_coins\r\n"
		+ "      followers\r\n"
		+ "      followers_count\r\n"
		+ "      hashtag\r\n"
		+ "      is_follow\r\n"
		+ "      is_master\r\n"
		+ "      maxDeliveryTime\r\n"
		+ "      minDeliveryTime\r\n"
		+ "      modified\r\n"
		+ "      name\r\n"
		+ "      nid\r\n"
		+ "      preferedBrandtags\r\n"
		+ "      preferedHashtags\r\n"
		+ "      profile_picture\r\n"
		+ "      published\r\n"
		+ "      social\r\n"
		+ "      star_count\r\n"
		+ "      tin\r\n"
		+ "      type\r\n"
		+ "      url\r\n"
		+ "      varifiedEmail\r\n"
		+ "      varifyStatus\r\n"
		+ "      website\r\n"
		+ "    }\r\n"
		+ "    service\r\n"
		+ "    sku\r\n"
		+ "    specificatios\r\n"
		+ "    status\r\n"
		+ "    stockQty\r\n"
		+ "    stockStatus\r\n"
		+ "    tags\r\n"
		+ "    totalQna\r\n"
		+ "    totalRating\r\n"
		+ "    totalSold\r\n"
		+ "  }\r\n"
		+ "}";


//⚡⚡⚡Custom Queries I Use ⚡⚡⚡

//QueryName >> brandsroducts
static String toGetCategoryIdQuery = "{\r\n"
		+ "  brandproducts {\r\n"
		+ "    _id\r\n"
		+ "    brand {\r\n"
		+ "      _id\r\n"
		+ "      hashtag\r\n"
		+ "      name\r\n"
		+ "      profile_picture\r\n"
		+ "    }\r\n"
		+ "    categories {\r\n"
		+ "      _id\r\n"
		+ "    }\r\n"
		+ "    clicks_count\r\n"
		+ "    country {\r\n"
		+ "      code\r\n"
		+ "      name\r\n"
		+ "    }\r\n"
		+ "    cta\r\n"
		+ "    currency\r\n"
		+ "    description\r\n"
		+ "  }\r\n"
		+ "}";
//QueryName >> parentCategories
static String toGetparentIdQuery = "{\r\n"
		+ "  parentCategories(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    ancestors {\r\n"
		+ "      _id\r\n"
		+ "      name\r\n"
		+ "      slug\r\n"
		+ "      type\r\n"
		+ "    }\r\n"
		+ "    createdAt\r\n"
		+ "    description\r\n"
		+ "    hasChild\r\n"
		+ "    name\r\n"
		+ "    slug\r\n"
		+ "    status\r\n"
		+ "    tags\r\n"
		+ "    totalProduct\r\n"
		+ "    type\r\n"
		+ "    updatedAt\r\n"
		+ "  }\r\n"
		+ "}";
//QueryName >> offerBanners
static String toGetOfferBannersQuery = "{\r\n"
		+ "  offerBanners(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    banner\r\n"
		+ "    bannerSize {\r\n"
		+ "      height\r\n"
		+ "      width\r\n"
		+ "    }\r\n"
		+ "    createdAt\r\n"
		+ "    description\r\n"
		+ "    filterKey\r\n"
		+ "    filterValue\r\n"
		+ "    position\r\n"
		+ "    products {\r\n"
		+ "      _id\r\n"
		+ "      brandName\r\n"
		+ "      category\r\n"
		+ "      costPrice\r\n"
		+ "      createdAt\r\n"
		+ "      currency\r\n"
		+ "      deliveryArea\r\n"
		+ "      deliveryType\r\n"
		+ "      description\r\n"
		+ "      id\r\n"
		+ "      isWishlist\r\n"
		+ "      modified\r\n"
		+ "      offerPrice\r\n"
		+ "      productName\r\n"
		+ "      rating\r\n"
		+ "      runningStock\r\n"
		+ "      salesPrice\r\n"
		+ "      service\r\n"
		+ "      sku\r\n"
		+ "      specificatios\r\n"
		+ "      status\r\n"
		+ "      stockQty\r\n"
		+ "      stockStatus\r\n"
		+ "      tags\r\n"
		+ "      totalQna\r\n"
		+ "      totalRating\r\n"
		+ "      totalSold\r\n"
		+ "    }\r\n"
		+ "    status\r\n"
		+ "    updatedAt\r\n"
		+ "    withProduct\r\n"
		+ "  }\r\n"
		+ "}";
//QueryName >> adminProductSearch
static String toGetadminProductSearchId = "{\r\n"
		+ "  adminProductSearch(\r\n"
		+ "    pageNumber: 10\r\n"
		+ "    perPage: 10\r\n"
		+ "    productSearchInput: {}\r\n"
		+ "  ) {\r\n"
		+ "    products {\r\n"
		+ "      _id\r\n"
		+ "      category\r\n"
		+ "      productName\r\n"
		+ "      stockQty\r\n"
		+ "      stockStatus\r\n"
		+ "    }\r\n"
		+ "    totalCount\r\n"
		+ "  }\r\n"
		+ "}";
//QueryName >> getUserListInfo
static String toGetUserListInfoQuery = "{\r\n"
		+ "  userList(endIndex: 10, startIndex: 1) {\r\n"
		+ "    _id\r\n"
		+ "    activityPoint {\r\n"
		+ "      totalPoint\r\n"
		+ "    }\r\n"
		+ "    fanfare_id {\r\n"
		+ "      f_id\r\n"
		+ "    }\r\n"
		+ "    firebaseRegToken\r\n"
		+ "    level\r\n"
		+ "    name\r\n"
		+ "    roles\r\n"
		+ "    signUpDevice {\r\n"
		+ "      deviceId\r\n"
		+ "      deviceModel\r\n"
		+ "    }\r\n"
		+ "    signUpType\r\n"
		+ "    social {\r\n"
		+ "      fb\r\n"
		+ "      google\r\n"
		+ "      instagram\r\n"
		+ "      twitter\r\n"
		+ "    }\r\n"
		+ "    status\r\n"
		+ "    wallet {\r\n"
		+ "      _id\r\n"
		+ "      fPoints\r\n"
		+ "      money\r\n"
		+ "    }\r\n"
		+ "  }\r\n"
		+ "}";
}
